/**
 * Town Planning & Land Development Workflow
 *
 * Module 4 (Compliance + Municipal Readiness) feature providing
 * SPLUMA land use application management, conditions tracking,
 * SDP oversight, subdivision coordination, and appeal handling.
 */

export * from './types';
export * from './services/accessControl';
export * from './services/municipalityConfig';
export {
  createApplication,
  getApplication,
  listApplicationsByProject,
  generateReferenceNumber,
  generateDocumentChecklist,
  updateDocumentChecklistItem,
  getCompletenessIndicator,
  validateSubmissionReadiness,
  CreateApplicationParamsSchema,
  DOCUMENT_CHECKLIST_TRANSITIONS,
  type CreateApplicationParams,
  type ActorContext,
  type ApplicationAuditEntry,
  type PassportWritePayload,
  type ApplicationAuditFn,
  type PassportFn,
  type DocChecklistItem,
  type ChecklistCompletenessIndicator,
  type SubmissionReadiness,
  type ChecklistItemUpdate,
} from './services/applicationEngine';
export {
  registerComment,
  updateCommentStatus,
  addResponse,
  getCommentsSummary,
  checkUnreviewedObjections,
  CommentInputSchema,
  CommentResponseInputSchema,
  COMMENT_STATUS_TRANSITIONS,
  type CommentInput,
  type CommentResponseInput,
  type CommentActor,
  type CommentAuditEntry,
  type CommentAuditFn,
  type CommentDeps,
  type CommentsSummary,
  type CommentRecord,
} from './services/commentRegister';
export {
  createCondition,
  updateConditionStatus,
  isConditionsCompliant,
  getConditionsSummary,
  checkOverdueConditions,
  updatePassportOnComplete,
  exposeToReadinessAdapter,
  ConditionInputSchema,
  CONDITION_STATUS_TRANSITIONS,
  type ConditionInput,
  type ConditionActor,
  type ConditionAuditEntry,
  type ConditionAuditFn,
  type PassportUpdatePayload,
  type PassportUpdateFn,
  type ReadinessPayload,
  type ReadinessAdapterFn,
  type ConditionDeps,
  type ConditionsSummary,
} from './services/conditionsRegister';
export {
  initiateSDP,
  updateChecklistItem,
  transitionSDPStage,
  validatePrerequisites,
  SDP_STAGE_TRANSITIONS,
  CHECKLIST_ITEM_TRANSITIONS,
  type SDPActor,
  type SDPAuditEntry,
  type SDPAuditFn,
  type SDPPassportPayload,
  type SDPPassportFn,
  type SDPReadinessPayload,
  type SDPReadinessFn,
  type SDPActionCentrePayload,
  type SDPActionCentreFn,
  type SDPDeps,
  type PrerequisiteResult,
} from './services/sdpEngine';
export {
  createSubdivisionRecord,
  generateSurveyorInstruction,
  transitionSGDiagramStage,
  transitionTitleDeedStage,
  SG_DIAGRAM_TRANSITIONS,
  TITLE_DEED_TRANSITIONS,
  type SubdivisionActor,
  type SubdivisionAuditEntry,
  type SubdivisionAuditFn,
  type SubdivisionPassportPayload,
  type SubdivisionPassportFn,
  type SubdivisionActionCentrePayload,
  type SubdivisionActionCentreFn,
  type TeamRouterPayload,
  type TeamRouterFn,
  type SubdivisionDeps,
  type SubdivisionCreateParams,
} from './services/subdivisionEngine';
export {
  fileAppeal,
  transitionAppealStage,
  calculatePrescribedDeadline,
  isWithinPrescribedPeriod,
  APPEAL_STAGE_TRANSITIONS,
  type AppealActor,
  type AppealInput,
  type AppealAuditEntry,
  type AppealAuditFn,
  type AppealPassportPayload,
  type AppealPassportFn,
  type AppealActionCentrePayload,
  type AppealActionCentreFn,
  type AppealDeps,
} from './services/appealTracker';
export {
  checkReadiness,
  markPlanningNotApplicable,
  getProgressIndicator,
  markPlanningPhaseComplete,
  type DependencyStatus,
  type ReadinessResult,
  type ProgressIndicator,
  type DependencyActor,
  type DependencyAuditEntry,
  type DependencyAuditFn,
  type DependencyPassportPayload,
  type DependencyPassportFn,
  type DependencyDeps,
} from './services/sequentialDependency';
export * from './adapters';
