export type HeritageImpactReadinessStatus = 'not_required' | 'blocked' | 'ready_for_human_review';
export interface HeritageImpactReadinessInput { scopeTags?: string[]; linearDevelopmentMeters?: number; bridgeLengthMeters?: number; siteCharacterChangeSqm?: number; rezoningSiteSqm?: number; evidence?: { spatialOverlayRef?: string; practitionerAppointmentRef?: string; hiaPackRef?: string; sahraOrPhraSubmissionRef?: string; heritageClearanceRef?: string }; checks?: { overlayScanComplete?: boolean; practitionerAppointed?: boolean; hiaReportsCompiled?: boolean; authorityProofTracked?: boolean } }
export function evaluateHeritageImpactReadiness(input: HeritageImpactReadinessInput) {
  const tags = (input.scopeTags ?? []).join(' ').toLowerCase();
  const triggers = Object.freeze({ linearDevelopment: (input.linearDevelopmentMeters ?? 0) > 300, bridge: (input.bridgeLengthMeters ?? 0) > 50, siteCharacterChange: (input.siteCharacterChangeSqm ?? 0) > 5000, rezoning: (input.rezoningSiteSqm ?? 0) > 10000, tagged: /heritage|sahra|phra|nhra|archaeolog|palaeontolog/.test(tags) });
  const required = Object.values(triggers).some(Boolean);
  const e = input.evidence ?? {}; const c = input.checks ?? {};
  const missing = required ? [!e.spatialOverlayRef && 'NHRA Section 38 spatial overlay scan reference', !e.practitionerAppointmentRef && 'registered heritage practitioner appointment reference', !e.hiaPackRef && 'cohesive HIA report pack reference', !e.sahraOrPhraSubmissionRef && 'SAHRA/PHRA proof tracking reference', !e.heritageClearanceRef && 'heritage clearance / authority response reference'].filter(Boolean) as string[] : [];
  const blockers = required ? [...missing.map((m) => `Missing ${m}.`), !c.overlayScanComplete && 'Spatial heritage overlay scan must be complete.', !c.practitionerAppointed && 'Heritage practitioner appointment must be confirmed.', !c.hiaReportsCompiled && 'Archaeological, palaeontological, and related HIA reports must be coordinated.', !c.authorityProofTracked && 'SAHRA/PHRA submission or clearance proof must be tracked.'].filter(Boolean) as string[] : [];
  const status: HeritageImpactReadinessStatus = !required ? 'not_required' : blockers.length ? 'blocked' : 'ready_for_human_review';
  return Object.freeze({ status, required, triggers, missingEvidence: missing, blockers, nextAction: { label: !required ? 'Confirm HIA workflow not required' : blockers.length ? 'Resolve NHRA Section 38 HIA blockers' : 'Approve HIA readiness pack', priority: blockers.length ? 'high' : 'low', target: 'municipal-tracker', requiresHumanConfirmation: true, automationLevel: 'advisory' as const }, audit: { prdSection: 'Section 54: Heritage Impact Assessments (NHRA Section 38 Triggers)' as const, noAutomaticAuthoritySubmission: true, humanReviewRequired: true } });
}
