export interface LabTestingReadinessInput { earthworksOrFoundations?: boolean; structuralConcreteCast?: boolean; evidence?: { sanasLabRef?: string; dcpResultsRef?: string; modAashtoRef?: string; cubeSamplingRef?: string; sevenDayCertificateRef?: string; twentyEightDayCertificateRef?: string; ncrRef?: string }; results?: { compactionPassed?: boolean; sevenDayMpa?: number; twentyEightDayMpa?: number; requiredMpa?: number; engineerApproved?: boolean } }
export function evaluateLabTestingReadiness(input: LabTestingReadinessInput) {
  const required = Boolean(input.earthworksOrFoundations || input.structuralConcreteCast);
  const e = input.evidence ?? {}; const r = input.results ?? {};
  const missing = required ? [!e.sanasLabRef && 'SANAS-accredited laboratory reference', input.earthworksOrFoundations && !e.dcpResultsRef && 'DCP compaction result reference', input.earthworksOrFoundations && !e.modAashtoRef && 'MOD AASHTO density test reference', input.structuralConcreteCast && !e.cubeSamplingRef && 'concrete cube sampling record', input.structuralConcreteCast && !e.sevenDayCertificateRef && '7-day cube crushing certificate', input.structuralConcreteCast && !e.twentyEightDayCertificateRef && '28-day cube crushing certificate'].filter(Boolean) as string[] : [];
  const failedStrength = input.structuralConcreteCast && r.requiredMpa !== undefined && r.twentyEightDayMpa !== undefined && r.twentyEightDayMpa < r.requiredMpa;
  const blockers = required ? [...missing.map((m) => `Missing ${m}.`), input.earthworksOrFoundations && r.compactionPassed !== true && 'Compaction test results must pass before foundation/concrete gate approval.', input.structuralConcreteCast && failedStrength && '28-day concrete strength is below structural specification and requires NCR/rectification.', failedStrength && !e.ncrRef && 'Failed concrete test must be linked to an NCR/rectification workflow.', !r.engineerApproved && 'Structural/civil engineer approval is required for lab-testing gate readiness.'].filter(Boolean) as string[] : [];
  return Object.freeze({ status: !required ? 'not_required' : blockers.length ? 'blocked' : 'ready_for_human_review', required, failedStrength: Boolean(failedStrength), missingEvidence: missing, blockers, nextAction: { label: !required ? 'Confirm lab testing not required' : blockers.length ? 'Resolve soil/concrete lab testing blockers' : 'Approve SANAS lab testing gate', priority: blockers.length ? 'high' : 'low', target: 'construction-os', requiresHumanConfirmation: true, automationLevel: 'advisory' as const }, audit: { prdSection: 'Section 55: Soil & Concrete Laboratory Testing (SANS 3001 & Compressive Strength Cube Tests)' as const, noAutomaticStructuralApproval: true, humanReviewRequired: true } });
}
