/**
 * Sample Data for Documents & Drawing Intelligence
 *
 * Simulated project documents, drawings, and revisions for
 * demonstration and testing. Represents a realistic mid-sized
 * architectural project through multiple phases.
 *
 * @module documents_drawing_intelligence
 */

import type {
  DocumentRecord,
  DocumentRevision,
  DrawingRecord,
} from '@/types/documentTypes';

export const tenantId = 'tenant-architex-demo';
export const projectId = 'project-sandton-upgrade';

/** 8 documents covering 6 of the 13 document types across 4 phases. */
export const sampleDocuments: DocumentRecord[] = [
  // ── Municipal Submission Phase ──
  {
    documentId: 'doc-a100',
    tenantId,
    projectId,
    title: 'Architectural Site Plan',
    documentType: 'drawing',
    discipline: 'architectural',
    phase: 'municipal_submission',
    status: 'issued',
    issuePurpose: 'for_municipal_submission',
    authorRole: 'architect',
    reviewerRole: 'architect',
    currentRevisionId: 'rev-a100-b',
    createdAt: '2026-06-01T08:00:00Z',
    updatedAt: '2026-06-02T08:00:00Z',
  },
  {
    documentId: 'doc-mun-form-001',
    tenantId,
    projectId,
    title: 'Municipal Application Form',
    documentType: 'municipal_form',
    discipline: 'general',
    phase: 'municipal_submission',
    status: 'draft',
    issuePurpose: 'for_municipal_submission',
    authorRole: 'architect',
    reviewerRole: 'client_developer',
    currentRevisionId: 'rev-mun-form-001-a',
    createdAt: '2026-06-02T08:00:00Z',
    updatedAt: '2026-06-04T08:00:00Z',
  },

  // ── Construction Execution Phase ──
  {
    documentId: 'doc-a101',
    tenantId,
    projectId,
    title: 'Ground Floor Plan',
    documentType: 'drawing',
    discipline: 'architectural',
    phase: 'construction_execution',
    status: 'issued',
    issuePurpose: 'for_construction',
    authorRole: 'architect',
    reviewerRole: 'architect',
    currentRevisionId: 'rev-a101-c',
    createdAt: '2026-06-01T08:00:00Z',
    updatedAt: '2026-06-03T08:00:00Z',
  },
  {
    documentId: 'doc-a102',
    tenantId,
    projectId,
    title: 'First Floor Plan (Superseded)',
    documentType: 'drawing',
    discipline: 'architectural',
    phase: 'construction_execution',
    status: 'superseded',
    issuePurpose: 'for_construction',
    authorRole: 'architect',
    reviewerRole: 'architect',
    currentRevisionId: 'rev-a102-b',
    createdAt: '2026-06-01T08:00:00Z',
    updatedAt: '2026-06-04T08:00:00Z',
  },
  {
    documentId: 'doc-a102-new',
    tenantId,
    projectId,
    title: 'First Floor Plan',
    documentType: 'drawing',
    discipline: 'architectural',
    phase: 'construction_execution',
    status: 'issued',
    issuePurpose: 'for_construction',
    authorRole: 'architect',
    reviewerRole: 'architect',
    currentRevisionId: 'rev-a102-c',
    createdAt: '2026-06-04T08:00:00Z',
    updatedAt: '2026-06-04T08:00:00Z',
  },

  // ── Tender Procurement Phase ──
  {
    documentId: 'doc-spec-001',
    tenantId,
    projectId,
    title: 'Outline Specification',
    documentType: 'specification',
    discipline: 'general',
    phase: 'tender_procurement',
    status: 'pending_review',
    issuePurpose: 'for_tender',
    authorRole: 'architect',
    reviewerRole: 'quantity_surveyor',
    currentRevisionId: 'rev-spec-001-a',
    createdAt: '2026-06-02T08:00:00Z',
    updatedAt: '2026-06-04T08:00:00Z',
  },

  // ── Closeout Phase ──
  {
    documentId: 'doc-closeout-001',
    tenantId,
    projectId,
    title: 'Closeout Pack',
    documentType: 'closeout_pack',
    discipline: 'general',
    phase: 'closeout',
    status: 'draft',
    issuePurpose: 'closeout',
    authorRole: 'contractor',
    reviewerRole: 'architect',
    currentRevisionId: 'rev-closeout-001-a',
    createdAt: '2026-06-03T08:00:00Z',
    updatedAt: '2026-06-04T08:00:00Z',
  },
  {
    documentId: 'doc-approval-001',
    tenantId,
    projectId,
    title: 'Municipal Approval Letter',
    documentType: 'approval_letter',
    discipline: 'general',
    phase: 'municipal_submission',
    status: 'draft',
    issuePurpose: 'for_municipal_submission',
    authorRole: 'client_developer',
    reviewerRole: 'architect',
    currentRevisionId: 'rev-approval-001-a',
    createdAt: '2026-06-05T08:00:00Z',
    updatedAt: '2026-06-05T08:00:00Z',
  },
];

/** 4 drawings with discipline coverage, supersession, and varied issue purposes. */
export const sampleDrawings: DrawingRecord[] = [
  {
    drawingId: 'drw-a100',
    documentId: 'doc-a100',
    drawingNumber: 'A-100',
    title: 'Site Plan',
    discipline: 'architectural',
    sheetType: 'site_plan',
    scale: '1:200',
    currentRevision: 'B',
    status: 'issued',
    issuePurpose: 'for_municipal_submission',
  },
  {
    drawingId: 'drw-a101',
    documentId: 'doc-a101',
    drawingNumber: 'A-101',
    title: 'Ground Floor Plan',
    discipline: 'architectural',
    sheetType: 'floor_plan',
    scale: '1:100',
    currentRevision: 'C',
    status: 'issued',
    issuePurpose: 'for_construction',
  },
  {
    drawingId: 'drw-a102-old',
    documentId: 'doc-a102',
    drawingNumber: 'A-102',
    title: 'First Floor Plan (Old)',
    discipline: 'architectural',
    sheetType: 'floor_plan',
    scale: '1:100',
    currentRevision: 'B',
    status: 'superseded',
    issuePurpose: 'for_construction',
    supersededByDrawingId: 'drw-a102-new',
  },
  {
    drawingId: 'drw-a102-new',
    documentId: 'doc-a102-new',
    drawingNumber: 'A-102',
    title: 'First Floor Plan',
    discipline: 'architectural',
    sheetType: 'floor_plan',
    scale: '1:100',
    currentRevision: 'C',
    status: 'issued',
    issuePurpose: 'for_construction',
  },
];

/** 4 revisions with supersession linking. */
export const sampleRevisions: DocumentRevision[] = [
  {
    revisionId: 'rev-a100-b',
    documentId: 'doc-a100',
    revisionCode: 'B',
    status: 'issued',
    issuePurpose: 'for_municipal_submission',
    issuedAt: '2026-06-02T08:00:00Z',
    authorUserId: 'u-architect-001',
    reviewerUserId: 'u-architect-002',
    notes: 'Issued for municipal submission.',
  },
  {
    revisionId: 'rev-a101-c',
    documentId: 'doc-a101',
    revisionCode: 'C',
    status: 'issued',
    issuePurpose: 'for_construction',
    issuedAt: '2026-06-03T08:00:00Z',
    authorUserId: 'u-architect-001',
    reviewerUserId: 'u-architect-002',
    notes: 'Issued for construction.',
  },
  {
    revisionId: 'rev-a102-b',
    documentId: 'doc-a102',
    revisionCode: 'B',
    status: 'superseded',
    issuePurpose: 'for_construction',
    issuedAt: '2026-06-02T08:00:00Z',
    supersededByRevisionId: 'rev-a102-c',
    authorUserId: 'u-architect-001',
    reviewerUserId: 'u-architect-002',
    notes: 'Superseded by revision C.',
  },
  {
    revisionId: 'rev-a102-c',
    documentId: 'doc-a102-new',
    revisionCode: 'C',
    status: 'issued',
    issuePurpose: 'for_construction',
    issuedAt: '2026-06-04T08:00:00Z',
    supersedesRevisionId: 'rev-a102-b',
    authorUserId: 'u-architect-001',
    reviewerUserId: 'u-architect-002',
    notes: 'Updated stair coordination.',
  },
];
