/**
 * Project Command Centre — Action Centre Service
 *
 * Manages actions and notifications generated by all Command Centre
 * subsystems. Persists to `projects/{projectId}/actions/` and
 * `projects/{projectId}/notifications/`.
 *
 * @module commandCentre/actionCentreService
 */

import {
  getDocs,
  addDoc,
  query,
  where,
} from 'firebase/firestore';
import { handleFirestoreError, OperationType } from '@/lib/firebase';
import { getDemoCol } from '@/demo-seed/demoFirestore';
import type { CommandCentreAction, Priority } from '@/services/commandCentre/types';

// ── ID Generation ────────────────────────────────────────────────────────────

function generateId(): string {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 11)}`;
}

// ── Collection Constants ─────────────────────────────────────────────────────

const PROJECTS_COL = 'projects';
const ACTIONS_COL = 'actions';
const NOTIFICATIONS_COL = 'notifications';

// ── Firestore Path Helpers ───────────────────────────────────────────────────

function actionsCollection(projectId: string) {
  if (!projectId) throw new Error('projectId is required');
  return getDemoCol(PROJECTS_COL, projectId, ACTIONS_COL);
}

function notificationsCollection(projectId: string) {
  if (!projectId) throw new Error('projectId is required');
  return getDemoCol(PROJECTS_COL, projectId, NOTIFICATIONS_COL);
}

// ── Filter Interface ─────────────────────────────────────────────────────────

export interface ActionFilters {
  type?: CommandCentreAction['type'];
  status?: CommandCentreAction['status'];
  assigneeId?: string;
  priority?: Priority;
}

// ── Notification Interface ───────────────────────────────────────────────────

export interface Notification {
  id: string;
  projectId: string;
  title: string;
  message: string;
  category: 'document' | 'rfi' | 'payment' | 'team' | 'milestone' | 'risk' | 'general';
  severity: 'info' | 'warning' | 'critical';
  icon?: string;
  sourceEntityType?: string;
  sourceEntityId?: string;
  readBy?: string[];
  createdAt: string;
}

// ── Action Stats Interface ───────────────────────────────────────────────────

export interface ActionStats {
  overdue: number;
  dueToday: number;
  upcoming: number;
  awaitingOthers: number;
  total: number;
}

// ── Action Management ────────────────────────────────────────────────────────

/**
 * Creates an action in the project Action Centre.
 * Actions are generated by subsystems (overdue tasks, unsigned certificates, etc.).
 */
export async function createAction(
  projectId: string,
  action: Omit<CommandCentreAction, 'id' | 'projectId' | 'createdAt'>,
): Promise<CommandCentreAction> {
  const now = new Date().toISOString();
  const newAction: CommandCentreAction = {
    ...action,
    id: generateId(),
    projectId,
    createdAt: now,
  };

  try {
    await addDoc(actionsCollection(projectId), newAction);
    return newAction;
  } catch (error) {
    handleFirestoreError(error, OperationType.CREATE, `${PROJECTS_COL}/${projectId}/${ACTIONS_COL}`);
    throw error;
  }
}

/**
 * Retrieves actions for a project with optional filters by type, status,
 * assignee, and priority.
 */
export async function getActions(
  projectId: string,
  filters?: ActionFilters,
): Promise<CommandCentreAction[]> {
  try {
    const constraints: Parameters<typeof query>[1][] = [];

    if (filters?.type) {
      constraints.push(where('type', '==', filters.type));
    }
    if (filters?.status) {
      constraints.push(where('status', '==', filters.status));
    }
    if (filters?.assigneeId) {
      constraints.push(where('assigneeId', '==', filters.assigneeId));
    }
    if (filters?.priority) {
      constraints.push(where('priority', '==', filters.priority));
    }

    const q = constraints.length > 0
      ? query(actionsCollection(projectId), ...constraints)
      : query(actionsCollection(projectId));

    const snap = await getDocs(q);
    return snap.docs.map((d) => ({ ...d.data(), id: d.id } as CommandCentreAction));
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, `${PROJECTS_COL}/${projectId}/${ACTIONS_COL}`);
    return [];
  }
}

/**
 * Computes action stats: overdue, due today, upcoming (7 days), awaiting others.
 */
export async function getActionStats(
  projectId: string,
  currentUserId?: string,
): Promise<ActionStats> {
  try {
    const actions = await getActions(projectId);
    const today = new Date().toISOString().slice(0, 10);
    const sevenDaysFromNow = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);

    const overdue = actions.filter(
      (a) => a.status === 'overdue' || (a.status === 'pending' && a.dueDate < today),
    ).length;

    const dueToday = actions.filter(
      (a) => a.status === 'pending' && a.dueDate.slice(0, 10) === today,
    ).length;

    const upcoming = actions.filter(
      (a) => a.status === 'pending' && a.dueDate > today && a.dueDate <= sevenDaysFromNow,
    ).length;

    const awaitingOthers = currentUserId
      ? actions.filter((a) => a.status === 'pending' && a.assigneeId !== currentUserId).length
      : 0;

    return {
      overdue,
      dueToday,
      upcoming,
      awaitingOthers,
      total: actions.length,
    };
  } catch {
    return { overdue: 0, dueToday: 0, upcoming: 0, awaitingOthers: 0, total: 0 };
  }
}

// ── Notification Management ──────────────────────────────────────────────────

/**
 * Creates a notification in the project notification feed.
 * Notifications are categorised with icon and severity level.
 */
export async function createNotification(
  projectId: string,
  notification: Omit<Notification, 'id' | 'projectId' | 'createdAt'>,
): Promise<Notification> {
  const now = new Date().toISOString();
  const newNotification: Notification = {
    ...notification,
    id: generateId(),
    projectId,
    createdAt: now,
  };

  try {
    await addDoc(notificationsCollection(projectId), newNotification);
    return newNotification;
  } catch (error) {
    handleFirestoreError(error, OperationType.CREATE, `${PROJECTS_COL}/${projectId}/${NOTIFICATIONS_COL}`);
    throw error;
  }
}

// ── Service Export ───────────────────────────────────────────────────────────

export const actionCentreService = {
  createAction,
  getActions,
  getActionStats,
  createNotification,
};

export default actionCentreService;
