/**
 * SpecForge Sample Data — Typed workspace and library constants for demo/dev mode.
 * Based on: Rosebank Mixed-Use Lobby + Office Fit-out project.
 */

import type { SpecForgeWorkspace, SpecProcurementEntry } from '@/types/specforgeTypes';

export const SAMPLE_WORKSPACE: SpecForgeWorkspace = {
  id: 'spec-ws-demo-001',
  projectId: 'architex-demo-project-rosebank-fitout',
  projectName: 'Rosebank Mixed-Use Lobby + Office Fit-out',
  municipality: 'City of Johannesburg',
  stage: 'Design Development / Tender Prep',
  profile: 'Commercial architectural + interior FF&E',
  revision: 'P01',
  issueStatus: 'draft',
  team: [
    { userId: 'u-arch-1', name: 'Project Architect', role: 'architect', responsibility: 'Lead specification author and issuer' },
    { userId: 'u-int-1', name: 'Interior Lead', role: 'bep', responsibility: 'FF&E and finishes selections' },
    { userId: 'u-qs-1', name: 'QS Reviewer', role: 'quantity_surveyor', responsibility: 'Budget checks and cost deltas' },
    { userId: 'u-client-1', name: 'Client Rep', role: 'client', responsibility: 'Client decision approvals' },
    { userId: 'u-contractor-1', name: 'Main Contractor', role: 'contractor', responsibility: 'Pricing and constructability feedback' },
  ],
  sections: [
    { id: 'sec-finishes', code: '09', title: 'Internal Finishes', discipline: 'architecture', ownerRole: 'architect', reviewerRole: 'quantity_surveyor', status: 'draft' },
    { id: 'sec-ffe', code: '12', title: 'FF&E and Loose Furniture', discipline: 'interiors', ownerRole: 'bep', reviewerRole: 'client', status: 'needs_review' },
    { id: 'sec-lighting', code: '26', title: 'Feature Lighting', discipline: 'electrical/interiors', ownerRole: 'bep', reviewerRole: 'engineer', status: 'draft' },
    { id: 'sec-joinery', code: '06', title: 'Custom Joinery', discipline: 'architecture/interiors', ownerRole: 'architect', reviewerRole: 'contractor', status: 'draft' },
  ],
  items: [
    {
      id: 'item-wall-tile-001',
      sectionId: 'sec-finishes',
      code: 'FIN-WT-001',
      title: 'Large format porcelain wall tile',
      room: 'Main Lobby',
      package: 'Finishes',
      discipline: 'architecture',
      supplier: 'Local tile supplier',
      model: '600x1200 matte porcelain',
      finish: 'Warm limestone',
      dimensions: '600 x 1200mm',
      drawingRefs: ['A-420 lobby elevations'],
      clauseRefs: ['SANS/NBR finish subject to professional verification'],
      budgetAllowance: 115000,
      estimatedCost: 128500,
      leadTimeDays: 21,
      clientDecision: true,
      ownerRole: 'architect',
      reviewerRole: 'quantity_surveyor',
      approverRole: 'client',
      status: 'needs_decision',
      sourceRevision: 'P01',
      supersededBy: null,
      sustainability: 'Low VOC adhesive required',
      warranty: 'Manufacturer standard tile warranty',
      notes: 'Confirm slip resistance for public lobby.',
    },
    {
      id: 'item-chair-001',
      sectionId: 'sec-ffe',
      code: 'FFE-CH-001',
      title: 'Reception lounge chair',
      room: 'Reception Lounge',
      package: 'FF&E',
      discipline: 'interiors',
      supplier: 'Furniture vendor',
      model: 'Contract lounge chair',
      finish: 'Sage fabric / oak legs',
      dimensions: '760W x 720D x 780H',
      drawingRefs: ['ID-301 furniture plan'],
      clauseRefs: ['Fire rating to be confirmed for occupancy'],
      budgetAllowance: 48000,
      estimatedCost: 46500,
      leadTimeDays: 56,
      clientDecision: true,
      ownerRole: 'bep',
      reviewerRole: 'quantity_surveyor',
      approverRole: 'client',
      status: 'approved',
      sourceRevision: 'P01',
      supersededBy: null,
      sustainability: 'FSC timber preference',
      warranty: '5-year frame warranty requested',
      notes: 'Mock-up sample required before bulk order.',
    },
    {
      id: 'item-pendant-001',
      sectionId: 'sec-lighting',
      code: 'LGT-PD-001',
      title: 'Custom reception pendant',
      room: 'Reception Desk',
      package: 'Electrical / Lighting',
      discipline: 'electrical/interiors',
      supplier: 'Lighting specialist',
      model: 'Bespoke linear pendant',
      finish: 'Brushed brass / opal diffuser',
      dimensions: '2400L x 180W',
      drawingRefs: ['E-210 reflected ceiling plan', 'ID-405 reception detail'],
      clauseRefs: ['Electrical engineer approval required'],
      budgetAllowance: 72000,
      estimatedCost: 91000,
      leadTimeDays: 84,
      clientDecision: false,
      ownerRole: 'bep',
      reviewerRole: 'engineer',
      approverRole: 'architect',
      status: 'draft',
      sourceRevision: 'P01',
      supersededBy: null,
      sustainability: 'LED driver replaceable; warm dim preferred',
      warranty: '3-year driver warranty',
      notes: 'Long-lead warning. Coordinate ceiling support and electrical load.',
    },
    {
      id: 'item-counter-001',
      sectionId: 'sec-joinery',
      code: 'JNY-RC-001',
      title: 'Reception counter joinery',
      room: 'Reception Desk',
      package: 'Joinery',
      discipline: 'architecture/interiors',
      supplier: 'Joinery subcontractor',
      model: 'Custom curved counter',
      finish: 'Oak veneer / solid surface top',
      dimensions: '4200L x 850D x 1050H',
      drawingRefs: ['A-550 reception counter details'],
      clauseRefs: ['Shop drawings required before manufacture'],
      budgetAllowance: 185000,
      estimatedCost: 179000,
      leadTimeDays: 42,
      clientDecision: false,
      ownerRole: 'architect',
      reviewerRole: 'contractor',
      approverRole: 'architect',
      status: 'draft',
      sourceRevision: 'P01',
      supersededBy: 'item-counter-002',
      sustainability: 'Low-formaldehyde board',
      warranty: '12-month defects liability minimum',
      notes: 'Current detail superseded by revised accessibility clearance sketch.',
    },
  ],
};

export const SAMPLE_PROCUREMENT_ENTRIES: SpecProcurementEntry[] = [
  {
    id: 'proc-item-chair-001',
    itemId: 'item-chair-001',
    itemCode: 'FFE-CH-001',
    itemTitle: 'Reception lounge chair',
    supplier: 'Furniture vendor',
    status: 'rfq_sent',
    rfqSentAt: '2026-06-10T09:00:00Z',
    notes: 'Awaiting mock-up sample confirmation.',
  },
  {
    id: 'proc-item-wall-tile-001',
    itemId: 'item-wall-tile-001',
    itemCode: 'FIN-WT-001',
    itemTitle: 'Large format porcelain wall tile',
    supplier: 'Local tile supplier',
    status: 'not_started',
    notes: 'Pending client decision.',
  },
  {
    id: 'proc-item-pendant-001',
    itemId: 'item-pendant-001',
    itemCode: 'LGT-PD-001',
    itemTitle: 'Custom reception pendant',
    supplier: 'Lighting specialist',
    status: 'quoted',
    rfqSentAt: '2026-05-28T10:00:00Z',
    quotedAt: '2026-06-05T14:30:00Z',
    quotedCost: 88500,
    notes: 'Quote received. Long-lead item — order early.',
  },
];
