// Standalone Tool Registry — All tools mapped by role for tile display
// Every tool is usable independently of any project/phase/workflow context.

import type { StandaloneToolDef } from '@/types/standaloneToolTypes'

export const STANDALONE_TOOL_REGISTRY: StandaloneToolDef[] = [
  // ===== Architect / BEP =====
  {
    id: 'fee_calculator',
    label: 'Professional Fee Calculator',
    category: 'fee_calculator',
    description: 'Calculate architectural/professional fees per SACAP/FeeDesk, ECSA, SACQSP or SACPLAN guidelines. Standalone — no project needed.',
    roles: ['architect', 'bep', 'engineer', 'quantity_surveyor', 'town_planner', 'energy_professional', 'fire_engineer', 'land_surveyor'],
    icon: 'Calculator',
    route: 'standalone/fee-calculator',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['fee', 'calculator', 'SACAP', 'ECSA', 'SACQSP', 'SACPLAN', 'tariff', 'proposal'],
    calculatorDefinitionId: 'fee_calculator_v1',
  },
  {
    id: 'fenestration_calc',
    label: 'Fenestration Compliance Calculator',
    category: 'compliance',
    description: 'Calculate minimum ventilation (5%) and lighting (10%) openings per SANS 10400-N. Independent room-by-room calc.',
    roles: ['architect', 'bep', 'engineer', 'energy_professional'],
    icon: 'Ruler',
    route: 'standalone/fenestration',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['SANS', '10400', 'fenestration', 'ventilation', 'lighting', 'compliance'],
    calculatorDefinitionId: 'fenestration_n_v1',
  },
  {
    id: 'rvalue_calc',
    label: 'R-Value / Thermal Calculator',
    category: 'compliance',
    description: 'Calculate wall/roof/floor thermal resistance per SANS 10400-XA. Material layers, orientation, climate zone.',
    roles: ['architect', 'bep', 'engineer', 'energy_professional'],
    icon: 'Thermometer',
    route: 'standalone/rvalue',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['SANS', '10400-XA', 'thermal', 'R-value', 'insulation', 'compliance'],
    calculatorDefinitionId: 'rvalue_calc_v1',
  },
  {
    id: 'ai_drawing_checker',
    label: 'AI Drawing Compliance Pre-check',
    category: 'drawing',
    description: 'Upload drawings for AI-powered SANS/NBR compliance pre-check. Advisory only — professional sign-off still required.',
    roles: ['architect', 'bep', 'engineer', 'energy_professional', 'fire_engineer', 'site_manager', 'freelancer'],
    icon: 'ScanSearch',
    route: 'drawing-checker',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['drawing', 'AI', 'compliance', 'SANS', 'review', 'check'],
    calculatorDefinitionId: 'ai_drawing_checker_v1',
  },
  {
    id: 'sans_forms',
    label: 'SANS / Compliance Forms Autofill',
    category: 'compliance',
    description: 'Generate compliance forms with project data prefilled. Standalone mode: manual data entry instead of project pull.',
    roles: ['architect', 'bep', 'engineer', 'energy_professional', 'fire_engineer', 'quantity_surveyor', 'town_planner', 'site_manager'],
    icon: 'FileText',
    route: 'sans-forms',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['SANS', 'compliance', 'forms', 'autofill', 'municipal'],
    calculatorDefinitionId: 'sans_forms_v1',
  },
  {
    id: 'drawing_register',
    label: 'Drawing Register (Standalone)',
    category: 'document_control',
    description: 'Create and manage a drawing register with issue numbers, revisions, status. No project context required — link later.',
    roles: ['architect', 'bep', 'engineer', 'quantity_surveyor', 'town_planner', 'energy_professional', 'fire_engineer', 'site_manager', 'developer', 'firm_admin', 'contractor'],
    icon: 'FileArchive',
    route: 'drawing-register',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['drawing', 'register', 'document', 'revision', 'control'],
    calculatorDefinitionId: 'drawing_register_v1',
  },
  {
    id: 'technical_brief',
    label: 'Technical Brief Editor (Standalone)',
    category: 'briefing',
    description: 'Draft a standalone technical brief with scope, assumptions, exclusions, deliverables list. Export or assign to a project later.',
    roles: ['architect', 'bep', 'engineer', 'energy_professional', 'fire_engineer', 'site_manager', 'developer', 'firm_admin'],
    icon: 'FileEdit',
    route: 'technical-brief',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['brief', 'scope', 'technical', 'deliverables'],
    calculatorDefinitionId: 'technical_brief_v1',
  },
  {
    id: 'doc_control_issue',
    label: 'Document Control Issue Sheet',
    category: 'document_control',
    description: 'Generate a document transmittal / issue sheet for drawings, specs, or reports. Standalone output with tracking number.',
    roles: ['architect', 'bep', 'engineer', 'contractor', 'subcontractor', 'quantity_surveyor', 'town_planner', 'energy_professional', 'fire_engineer', 'site_manager', 'developer', 'firm_admin'],
    icon: 'Send',
    route: 'standalone/doc-issue',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['document', 'transmittal', 'issue', 'tracking', 'control'],
    calculatorDefinitionId: 'doc_control_issue_v1',
  },
  {
    id: 'cpd_standalone',
    label: 'CPD Assessment (Standalone)',
    category: 'cpd',
    description: 'Take a CPD assessment to earn credits. Independent of any project — personal professional development record.',
    roles: ['architect', 'bep', 'engineer', 'quantity_surveyor', 'town_planner', 'energy_professional', 'fire_engineer', 'site_manager', 'developer', 'firm_admin', 'platform_admin', 'land_surveyor'],
    icon: 'BookOpen',
    route: 'cpd-assessment',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['CPD', 'assessment', 'credits', 'SACAP', 'ECSA', 'development'],
    calculatorDefinitionId: 'cpd_standalone_v1',
  },

  // ===== Client =====
  {
    id: 'soft_cost_estimator',
    label: 'Soft Cost Estimator',
    category: 'fee_calculator',
    description: 'Estimate likely professional fees + municipal costs for a project. No appointment needed — planning-stage projection.',
    roles: ['client', 'developer'],
    icon: 'Calculator',
    route: 'standalone/soft-cost',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['cost', 'estimate', 'professional', 'municipal', 'budget'],
    calculatorDefinitionId: 'soft_cost_estimator_v1',
  },
  {
    id: 'brief_wizard',
    label: 'Guided Brief Wizard (Standalone)',
    category: 'briefing',
    description: 'Create or refine a project brief independently. Save as draft and assign to an architect later.',
    roles: ['client'],
    icon: 'ClipboardEdit',
    route: 'client-intake',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['brief', 'wizard', 'client', 'requirements'],
    calculatorDefinitionId: 'brief_wizard_v1',
  },
  {
    id: 'proposal_comparison',
    label: 'BEP Proposal Comparison',
    category: 'proposal',
    description: 'Compare professional proposals side-by-side: fee, scope, exclusions, timeline. No project context required.',
    roles: ['client'],
    icon: 'Scale',
    route: 'client-proposals',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['proposal', 'comparison', 'BEP', 'fee', 'selection'],
    calculatorDefinitionId: 'proposal_comparison_v1',
  },
  {
    id: 'progress_viewer',
    label: 'Progress Report Viewer',
    category: 'general',
    description: 'View project progress reports by reference number. Enter any project reference — Architex or external.',
    roles: ['client'],
    icon: 'Clock',
    route: 'client-progress',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['progress', 'report', 'status', 'client'],
    calculatorDefinitionId: 'progress_viewer_v1',
  },
  {
    id: 'payment_dashboard',
    label: 'Payment Status Dashboard',
    category: 'payment',
    description: 'View payment status for any active project or standalone claim references. No active project needed.',
    roles: ['client', 'contractor', 'subcontractor', 'supplier', 'energy_professional', 'fire_engineer', 'developer', 'firm_admin'],
    icon: 'CreditCard',
    route: 'payments',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['payment', 'status', 'claim', 'invoice', 'tracking'],
    calculatorDefinitionId: 'payment_dashboard_v1',
  },

  // ===== Contractor =====
  {
    id: 'boq_takeoff',
    label: 'BoQ / BoM Takeoff Tool',
    category: 'estimating',
    description: 'Create a bill of quantities or materials takeoff from scratch. Manual quantity entry with rate build-up and total calculation.',
    roles: ['contractor', 'subcontractor', 'quantity_surveyor', 'architect'],
    icon: 'Ruler',
    route: 'standalone/boq-takeoff',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['BoQ', 'BoM', 'takeoff', 'quantity', 'estimate', 'material'],
    calculatorDefinitionId: 'boq_takeoff_v1',
  },
  {
    id: 'site_diary_entry',
    label: 'Site Diary Standalone Entry',
    category: 'site_management',
    description: 'Capture a standalone site diary entry: weather, labour, plant, deliveries, activities, delays, photos.',
    roles: ['contractor', 'subcontractor', 'site_manager'],
    icon: 'ClipboardList',
    route: 'standalone/site-diary',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['site', 'diary', 'daily', 'log', 'progress', 'photo'],
    calculatorDefinitionId: 'site_diary_entry_v1',
  },
  {
    id: 'rfi_generator',
    label: 'RFI / Site Instruction Generator',
    category: 'site_management',
    description: 'Draft a Request for Information or Site Instruction from scratch. Independent of any project record.',
    roles: ['contractor', 'subcontractor', 'architect', 'engineer', 'site_manager'],
    icon: 'MessageSquare',
    route: 'standalone/rfi',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['RFI', 'instruction', 'site', 'communication', 'query'],
    calculatorDefinitionId: 'rfi_generator_v1',
  },
  {
    id: 'workforce_timesheet',
    label: 'Workforce Timesheet / Payroll Export',
    category: 'workforce',
    description: 'Create a workforce timesheet with hours, rates, cost codes, and PAYE/UIF/SDL fields. Export to payroll format.',
    roles: ['contractor', 'subcontractor', 'site_manager'],
    icon: 'Users',
    route: 'standalone/timesheet',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['timesheet', 'workforce', 'labour', 'payroll', 'attendance'],
    calculatorDefinitionId: 'workforce_timesheet_v1',
  },
  {
    id: 'plant_register',
    label: 'Plant & Equipment Register',
    category: 'plant_equipment',
    description: 'Maintain a standalone register of plant/equipment: asset details, hire rates, service reminders, utilisation.',
    roles: ['contractor', 'subcontractor', 'site_manager'],
    icon: 'Wrench',
    route: 'standalone/plant-register',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['plant', 'equipment', 'asset', 'register', 'hire'],
    calculatorDefinitionId: 'plant_register_v1',
  },
  {
    id: 'tender_bid_bench',
    label: 'Tender / Bid Workbench',
    category: 'tendering',
    description: 'Prepare a tender or bid response independently. BOQ pricing, methodology, exclusions, qualifications.',
    roles: ['contractor', 'subcontractor', 'supplier'],
    icon: 'Briefcase',
    route: 'procurement',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['tender', 'bid', 'pricing', 'BOQ', 'submission'],
    calculatorDefinitionId: 'tender_bid_bench_v1',
  },
  {
    id: 'snag_creator',
    label: 'Snag List Creator',
    category: 'site_management',
    description: 'Create a standalone snag/punch list with photos, location, due dates, responsible party. No project or inspection needed.',
    roles: ['contractor', 'subcontractor', 'architect', 'client', 'site_manager'],
    icon: 'ClipboardCheck',
    route: 'standalone/snag-list',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['snag', 'punch', 'defect', 'inspection', 'closeout'],
    calculatorDefinitionId: 'snag_creator_v1',
  },
  {
    id: 'material_procurement',
    label: 'Material Procurement / Order List',
    category: 'procurement',
    description: 'Create a standalone material procurement list from takeoff or manual entry. Convert to purchase order-ready format.',
    roles: ['contractor', 'subcontractor', 'supplier'],
    icon: 'Package',
    route: 'standalone/procurement-list',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['material', 'procurement', 'order', 'purchase', 'list'],
    calculatorDefinitionId: 'material_procurement_v1',
  },
  {
    id: 'payment_claim_builder',
    label: 'Payment Claim Builder',
    category: 'payment',
    description: 'Build a payment claim from timesheet + material + plant data. Standalone calculation with progress evidence upload.',
    roles: ['contractor', 'subcontractor', 'freelancer'],
    icon: 'Receipt',
    route: 'standalone/payment-claim',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['payment', 'claim', 'invoice', 'progress', 'evidence'],
  },

  // ===== Subcontractor =====
  {
    id: 'shop_drawing_submission',
    label: 'Shop Drawing & Sample Submission',
    category: 'document_control',
    description: 'Submit shop drawings and material samples independently. Tag with project reference later.',
    roles: ['subcontractor', 'supplier'],
    icon: 'Upload',
    route: 'standalone/shop-drawing',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['shop drawing', 'sample', 'submission', 'approval'],
  },
  {
    id: 'package_scope_viewer',
    label: 'Package Scope Viewer',
    category: 'general',
    description: 'Enter a subcontract package reference to view scope, deliverables, and payment terms. Standalone lookup tool.',
    roles: ['subcontractor'],
    icon: 'Search',
    route: 'packages',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['package', 'scope', 'subcontract', 'deliverables'],
  },
  {
    id: 'snag_evidence_upload',
    label: 'Snag / Closeout Evidence Upload',
    category: 'closeout',
    description: 'Upload evidence of completed snag items or defects closeout. Standalone with optional project reference.',
    roles: ['subcontractor', 'contractor'],
    icon: 'Camera',
    route: 'standalone/snag-evidence',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['snag', 'closeout', 'evidence', 'photo', 'defect'],
  },
  {
    id: 'rfi_response',
    label: 'RFI / Site Instruction Response',
    category: 'site_management',
    description: 'Respond to an RFI or site instruction. Enter RFI reference manually or create a new standalone response thread.',
    roles: ['subcontractor', 'contractor', 'supplier'],
    icon: 'Reply',
    route: 'standalone/rfi-response',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['RFI', 'response', 'instruction', 'site'],
  },

  // ===== Supplier =====
  {
    id: 'catalogue_manager',
    label: 'Catalogue / Product Data Manager',
    category: 'supplier',
    description: 'Manage product catalogue, alternatives, availability, prices, and lead times. Standalone supplier dashboard.',
    roles: ['supplier'],
    icon: 'Book',
    route: 'standalone/catalogue',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['catalogue', 'product', 'data', 'price', 'supplier'],
  },
  {
    id: 'quote_response',
    label: 'Quote Response Form',
    category: 'supplier',
    description: 'Submit a quote in response to an RFQ. Enter RFQ number manually or create a proactive quote.',
    roles: ['supplier'],
    icon: 'FileInput',
    route: 'packages',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['quote', 'RFQ', 'response', 'pricing'],
  },
  {
    id: 'delivery_note',
    label: 'Delivery Note Builder',
    category: 'supplier',
    description: 'Create a delivery note with line items, quantities, PO reference, delivery details. No purchase order required.',
    roles: ['supplier', 'contractor'],
    icon: 'Truck',
    route: 'standalone/delivery-note',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['delivery', 'note', 'POD', 'goods', 'transport'],
  },
  {
    id: 'warranty_upload',
    label: 'Warranty Certificate Uploader',
    category: 'closeout',
    description: 'Upload warranty certificates and product documentation. Standalone with optional project/PO reference.',
    roles: ['supplier', 'contractor', 'subcontractor'],
    icon: 'Shield',
    route: 'standalone/warranty',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['warranty', 'certificate', 'upload', 'documentation'],
  },

  // ===== Freelancer =====
  {
    id: 'cad_upload_check',
    label: 'CAD / BIM File Upload + Drawing Checker',
    category: 'drawing',
    description: 'Upload CAD/BIM files for AI drawing check. Standalone — no BEP project assignment required. Supervisor sign-off gate applies.',
    roles: ['freelancer'],
    icon: 'FileUp',
    route: 'drawing-checker',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['CAD', 'BIM', 'drawing', 'upload', 'check', 'freelancer'],
  },
  {
    id: 'freelancer_timesheet',
    label: 'Timesheet / Claim Builder',
    category: 'freelancer',
    description: 'Submit a standalone timesheet with hours, rate, and deliverable notes. Convert to claim with supervisor approval gate.',
    roles: ['freelancer'],
    icon: 'Clock',
    route: 'standalone/freelancer-timesheet',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['timesheet', 'claim', 'freelancer', 'hours', 'payment'],
  },
  {
    id: 'deliverable_submission',
    label: 'Deliverable Submission with Sign-off',
    category: 'freelancer',
    description: 'Submit a standalone deliverable with supervisor sign-off gate. Independent of any active BEP engagement.',
    roles: ['freelancer'],
    icon: 'Send',
    route: 'freelancer-submissions',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['deliverable', 'submission', 'sign-off', 'freelancer', 'supervisor'],
  },
  {
    id: 'freelancer_resource_centre',
    label: 'Resource Centre / Checklists',
    category: 'resource_centre',
    description: 'Access checklists, templates, and reference resources as a freelancer. Quality control tools independent of projects.',
    roles: ['freelancer', 'architect', 'bep', 'engineer', 'energy_professional', 'fire_engineer', 'site_manager', 'developer', 'firm_admin', 'platform_admin'],
    icon: 'Library',
    route: 'resource-centre',
    standaloneOnly: false,
    requiresInput: false,
    canExport: false,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['resource', 'checklist', 'template', 'reference', 'freelancer'],
  },

  // ===== Admin =====
  {
    id: 'admin_governance',
    label: 'Governance Console',
    category: 'admin_governance',
    description: 'System-wide governance overview: users, projects, verification, disputes, audit queues.',
    roles: ['admin'],
    icon: 'Settings2',
    route: 'admin-console',
    standaloneOnly: false,
    requiresInput: false,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['admin', 'governance', 'console', 'oversight'],
  },
  {
    id: 'audit_trail_viewer',
    label: 'Audit Trail Viewer',
    category: 'admin_governance',
    description: 'Browse all auditable actions across the platform. Filter by user, action, date range, entity type.',
    roles: ['admin'],
    icon: 'History',
    route: 'disputes',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['audit', 'trail', 'history', 'admin', 'compliance'],
  },
  {
    id: 'ai_review_queue',
    label: 'AI Review Queue',
    category: 'admin_governance',
    description: 'Review AI-generated outputs that require human confirmation before release or action.',
    roles: ['admin'],
    icon: 'Bot',
    route: 'ai',
    standaloneOnly: false,
    requiresInput: false,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['AI', 'review', 'queue', 'approval', 'governance'],
  },
  {
    id: 'payment_rate_config',
    label: 'Payment Rate Configurator',
    category: 'admin_governance',
    description: 'Configure payment rails, platform fees, escrow settings, and tariff tables.',
    roles: ['admin'],
    icon: 'DollarSign',
    route: 'payments',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['payment', 'rate', 'fee', 'escrow', 'config', 'admin'],
  },
  {
    id: 'user_verification_console',
    label: 'User Verification Console',
    category: 'admin_governance',
    description: 'Verify user identities, professional registrations, PI insurance documents. Independent dashboard.',
    roles: ['admin'],
    icon: 'ShieldCheck',
    route: 'standalone/verification-console',
    standaloneOnly: true,
    requiresInput: false,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['verification', 'user', 'identity', 'registration', 'admin'],
  },
  {
    id: 'fee_tariff_editor',
    label: 'Fee / Tariff Table Editor',
    category: 'admin_governance',
    description: 'Edit professional fee guideline tables, tariff brackets, and calculator data versions.',
    roles: ['admin'],
    icon: 'Table',
    route: 'standalone/tariff-editor',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['fee', 'tariff', 'table', 'editor', 'calculator', 'admin'],
  },

  // ===== Energy Professional =====
  {
    id: 'xa_compliance_calc',
    label: 'XA Energy Compliance Calculator',
    category: 'compliance',
    description: 'Calculate SANS 10400-XA energy compliance: insulation, glazing, orientation, and HVAC requirements. Standalone building energy check.',
    roles: ['energy_professional', 'architect', 'bep'],
    icon: 'Zap',
    route: 'sans-forms',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['SANS', '10400-XA', 'energy', 'compliance', 'insulation', 'glazing', 'HVAC'],
    calculatorDefinitionId: 'xa_energy_compliance_v1',
  },
  {
    id: 'energy_certificate',
    label: 'Energy Performance Certificate Prep',
    category: 'compliance',
    description: 'Prepare energy performance certificate data: building envelope, systems, and energy usage inputs. Standalone certificate worksheet.',
    roles: ['energy_professional'],
    icon: 'FileCheck',
    route: 'design',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['energy', 'certificate', 'performance', 'compliance', 'EPC'],
    calculatorDefinitionId: 'energy_certificate_v1',
  },

  // ===== Fire Engineer =====
  {
    id: 'fire_rational_design',
    label: 'Rational Fire Design Worksheet',
    category: 'compliance',
    description: 'Document rational fire design: passive fire protection, escape routes, fire resistance ratings, and active systems. Standalone design record.',
    roles: ['fire_engineer', 'architect', 'bep'],
    icon: 'Flame',
    route: 'design',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['fire', 'rational', 'design', 'SANS 10400-T', 'escape', 'passive'],
  },
  {
    id: 'fire_compliance_check',
    label: 'SANS 10400-T Compliance Checklist',
    category: 'compliance',
    description: 'Run a SANS 10400-T fire compliance checklist: fire doors, travel distances, compartmentation, and fire detection. Advisory pre-check.',
    roles: ['fire_engineer', 'architect', 'bep', 'engineer'],
    icon: 'ClipboardCheck',
    route: 'sans-forms',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['SANS', '10400-T', 'fire', 'compliance', 'checklist', 'doors', 'escape'],
  },

  // ===== Developer =====
  {
    id: 'feasibility_estimator',
    label: 'Project Feasibility & Budget Estimator',
    category: 'fee_calculator',
    description: 'Estimate project feasibility: professional fees, municipal costs, construction budget, and timeline. Standalone planning-stage tool.',
    roles: ['developer', 'client'],
    icon: 'TrendingUp',
    route: 'client-intake',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['feasibility', 'budget', 'cost', 'estimate', 'developer', 'planning'],
  },
  {
    id: 'stage_gate_review',
    label: 'Stage Gate Review & Decision Log',
    category: 'general',
    description: 'Document stage gate decisions: scope, budget, timeline, risk assessment, and approval records. Standalone governance log.',
    roles: ['developer', 'client'],
    icon: 'DoorOpen',
    route: 'client-progress',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['stage', 'gate', 'review', 'decision', 'governance', 'approval'],
  },

  // ===== Firm Admin =====
  {
    id: 'staff_cpd_tracker',
    label: 'Staff CPD Compliance Tracker',
    category: 'cpd',
    description: 'Track staff CPD compliance: credits earned, outstanding, expiry dates, and professional body requirements. Standalone firm-wide tracker.',
    roles: ['firm_admin', 'admin'],
    icon: 'Users',
    route: 'cpd-assessment',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['CPD', 'staff', 'compliance', 'tracking', 'firm', 'professional'],
  },
  {
    id: 'firm_document_register',
    label: 'Firm-Wide Document Register',
    category: 'document_control',
    description: 'Maintain a firm-wide document register: drawing issues, revision control, transmittals, and document status across all projects.',
    roles: ['firm_admin', 'architect', 'bep', 'engineer'],
    icon: 'FileArchive',
    route: 'drawing-register',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['document', 'register', 'firm', 'drawing', 'control', 'revision'],
  },

  // ===== Platform Admin =====
  {
    id: 'platform_settings',
    label: 'Platform Configuration Console',
    category: 'admin_governance',
    description: 'Configure platform-wide settings: feature flags, rate limits, role permissions, and system defaults. Standalone admin console.',
    roles: ['platform_admin', 'admin'],
    icon: 'Settings2',
    route: 'admin-console',
    standaloneOnly: false,
    requiresInput: false,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['platform', 'configuration', 'settings', 'admin', 'governance'],
  },
  {
    id: 'system_health_monitor',
    label: 'System Health & Audit Monitor',
    category: 'admin_governance',
    description: 'Monitor system health: audit trail density, error rates, active sessions, and integration status. Standalone monitoring dashboard.',
    roles: ['platform_admin', 'admin'],
    icon: 'Activity',
    route: 'disputes',
    standaloneOnly: false,
    requiresInput: false,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['system', 'health', 'monitor', 'audit', 'admin', 'performance'],
  },

  // ===== Construction Admin & Compliance =====
  {
    id: 'council_navigator',
    label: 'SA Council Drawing Compliance Navigator',
    category: 'compliance',
    description: 'Municipality-specific drawing submission requirements for South African local authorities.',
    roles: ['architect', 'bep', 'engineer', 'energy_professional', 'fire_engineer', 'town_planner', 'admin'],
    icon: 'MapPin',
    route: 'standalone/council-navigator',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['council', 'municipality', 'drawing', 'compliance', 'submission', 'SA'],
    calculatorDefinitionId: 'council_navigator_v1',
  },
  {
    id: 'ncr_manager',
    label: 'NCR Manager',
    category: 'site_management',
    description: 'Non-conformance report management — defect identification, tracking, and resolution.',
    roles: ['architect', 'bep', 'contractor', 'subcontractor', 'site_manager', 'engineer', 'admin'],
    icon: 'AlertTriangle',
    route: 'standalone/ncr-manager',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['NCR', 'non-conformance', 'defect', 'quality', 'site', 'inspection'],
    calculatorDefinitionId: 'ncr_manager_v1',
  },
  {
    id: 'site_instruction_manager',
    label: 'Site Instruction Manager',
    category: 'site_management',
    description: 'Formal site instruction issuance, acknowledgement, and tracking workflows.',
    roles: ['architect', 'bep', 'contractor', 'subcontractor', 'site_manager', 'engineer', 'admin'],
    icon: 'FileText',
    route: 'standalone/site-instructions',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['instruction', 'site', 'directive', 'construction', 'acknowledgement', 'tracking'],
    calculatorDefinitionId: 'site_instruction_manager_v1',
  },
  {
    id: 'contract_admin_workspace',
    label: 'Contract Administration Workspace',
    category: 'construction_admin',
    description: 'Claims, variations, EoT, notices, payment schedules, and contract data in one workspace.',
    roles: ['architect', 'bep', 'quantity_surveyor', 'contractor', 'subcontractor', 'site_manager', 'engineer', 'admin'],
    icon: 'Briefcase',
    route: 'standalone/contract-admin',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['contract', 'claims', 'variations', 'EoT', 'notices', 'payment', 'JBCC', 'NEC', 'GCC', 'FIDIC'],
    calculatorDefinitionId: 'contract_admin_workspace_v1',
  },
  {
    id: 'contractor_compliance_dashboard',
    label: 'Contractor & Supplier Compliance Dashboard',
    category: 'compliance',
    description: 'Compliance gate visibility — check statuses, expired certifications, and access control.',
    roles: ['architect', 'bep', 'contractor', 'subcontractor', 'supplier', 'site_manager', 'quantity_surveyor', 'admin'],
    icon: 'ShieldCheck',
    route: 'standalone/contractor-compliance',
    standaloneOnly: false,
    requiresInput: false,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['contractor', 'supplier', 'compliance', 'COIDA', 'H&S', 'B-BBEE', 'tax', 'gate'],
    calculatorDefinitionId: 'contractor_compliance_v1',
  },

  // ===== Site Manager (additional) =====
  {
    id: 'hs_compliance',
    label: 'H&S Compliance Checklist',
    category: 'site_management',
    description: 'Run a health and safety compliance checklist: site induction, PPE, scaffolding, excavation, and emergency procedures. Standalone H&S log.',
    roles: ['site_manager', 'contractor', 'subcontractor'],
    icon: 'Shield',
    route: 'construction',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['H&S', 'health', 'safety', 'compliance', 'checklist', 'site'],
  },

  // ===== Quantity Surveyor (additional) =====
  {
    id: 'valuation_cert',
    label: 'Payment Valuation Certificate',
    category: 'payment',
    description: 'Prepare a payment valuation certificate: progress measurement, retentions, VAT, and certified amounts. Standalone valuation worksheet.',
    roles: ['quantity_surveyor', 'architect', 'contractor'],
    icon: 'Receipt',
    route: 'payments',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['valuation', 'payment', 'certificate', 'retention', 'VAT', 'QS'],
  },

  // ===== Engineer's Calculation Hub =====
  {
    id: 'engineers_calc_hub',
    label: "Engineer's Calculation Hub",
    category: 'compliance',
    description: '53 professional-grade engineering calculators across 8 disciplines with SANS compliance checking',
    roles: ['engineer', 'architect', 'bep', 'energy_professional', 'fire_engineer', 'quantity_surveyor', 'site_manager'],
    icon: 'Calculator',
    route: 'standalone/engineers-calc-hub',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['engineering', 'calculator', 'SANS', 'structural', 'steel', 'concrete', 'timber', 'geotechnical', 'fire', 'electrical', 'mechanical', 'compliance'],
    calculatorDefinitionId: 'engineers_calc_hub_v1',
  },

  // ===== Town Planner (additional) =====
  {
    id: 'zoning_check',
    label: 'Zoning Compliance Checker',
    category: 'compliance',
    description: 'Check zoning compliance against land-use scheme: use rights, coverage, FAR, setbacks, parking, and height restrictions. Advisory pre-check.',
    roles: ['town_planner', 'architect', 'developer'],
    icon: 'Map',
    route: 'design',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['zoning', 'land-use', 'compliance', 'scheme', 'coverage', 'FAR'],
  },
]

export function getToolsForRole(role: string): StandaloneToolDef[] {
  return STANDALONE_TOOL_REGISTRY.filter(t => t.roles.includes(role))
}

export function getToolById(id: string): StandaloneToolDef | undefined {
  return STANDALONE_TOOL_REGISTRY.find(t => t.id === id)
}

export function searchTools(query: string, role: string): StandaloneToolDef[] {
  const q = query.toLowerCase().trim()
  if (!q) return getToolsForRole(role)
  return getToolsForRole(role).filter(t =>
    t.label.toLowerCase().includes(q) ||
    t.description.toLowerCase().includes(q) ||
    t.tags.some(tag => tag.toLowerCase().includes(q)) ||
    t.category.toLowerCase().includes(q)
  )
}

export function getToolsByCategory(role: string): Record<string, StandaloneToolDef[]> {
  const tools = getToolsForRole(role)
  const grouped: Record<string, StandaloneToolDef[]> = {}
  for (const t of tools) {
    if (!grouped[t.category]) grouped[t.category] = []
    grouped[t.category].push(t)
  }
  return grouped
}
