// Standalone Tool Registry — All tools mapped by role for tile display
// Every tool is usable independently of any project/phase/workflow context.

import type { StandaloneToolDef } from '@/types/standaloneToolTypes'

export const STANDALONE_TOOL_REGISTRY: StandaloneToolDef[] = [
  // ===== Architect / BEP =====
  {
    id: 'fee_calculator',
    label: 'Professional Fee Calculator',
    category: 'fee_calculator',
    description: 'Calculate architectural/professional fees per SACAP/FeeDesk, ECSA, SACQSP or SACPLAN guidelines. Standalone — no project needed.',
    roles: ['architect', 'bep', 'engineer', 'quantity_surveyor', 'town_planner', 'land_surveyor', 'cpm', 'landscape_architect', 'interior_designer'],
    icon: 'Calculator',
    route: 'standalone/fee-calculator',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['fee', 'calculator', 'SACAP', 'ECSA', 'SACQSP', 'SACPLAN', 'tariff', 'proposal'],
  },
  {
    id: 'fenestration_calc',
    label: 'Fenestration Compliance Calculator',
    category: 'compliance',
    description: 'Calculate minimum ventilation (5%) and lighting (10%) openings per SANS 10400-N. Independent room-by-room calc.',
    roles: ['architect', 'bep', 'engineer'],
    icon: 'Ruler',
    route: 'standalone/fenestration',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['SANS', '10400', 'fenestration', 'ventilation', 'lighting', 'compliance'],
  },
  {
    id: 'rvalue_calc',
    label: 'R-Value / Thermal Calculator',
    category: 'compliance',
    description: 'Calculate wall/roof/floor thermal resistance per SANS 10400-XA. Material layers, orientation, climate zone.',
    roles: ['architect', 'bep', 'engineer'],
    icon: 'Thermometer',
    route: 'standalone/rvalue',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['SANS', '10400-XA', 'thermal', 'R-value', 'insulation', 'compliance'],
  },
  {
    id: 'ai_drawing_checker',
    label: 'AI Drawing Compliance Pre-check',
    category: 'drawing',
    description: 'Upload drawings for AI-powered SANS/NBR compliance pre-check. Advisory only — professional sign-off still required.',
    roles: ['architect', 'bep', 'engineer', 'freelancer'],
    icon: 'ScanSearch',
    route: 'drawing-checker',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['drawing', 'AI', 'compliance', 'SANS', 'review', 'check'],
  },
  {
    id: 'sans_forms',
    label: 'SANS / Compliance Forms Autofill',
    category: 'compliance',
    description: 'Generate compliance forms with project data prefilled. Standalone mode: manual data entry instead of project pull.',
    roles: ['architect', 'bep', 'engineer'],
    icon: 'FileText',
    route: 'sans-forms',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['SANS', 'compliance', 'forms', 'autofill', 'municipal'],
  },
  {
    id: 'drawing_register',
    label: 'Drawing Register (Standalone)',
    category: 'document_control',
    description: 'Create and manage a drawing register with issue numbers, revisions, status. No project context required — link later.',
    roles: ['architect', 'bep', 'engineer', 'contractor'],
    icon: 'FileArchive',
    route: 'drawing-register',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['drawing', 'register', 'document', 'revision', 'control'],
  },
  {
    id: 'technical_brief',
    label: 'Technical Brief Editor (Standalone)',
    category: 'briefing',
    description: 'Draft a standalone technical brief with scope, assumptions, exclusions, deliverables list. Export or assign to a project later.',
    roles: ['architect', 'bep', 'engineer'],
    icon: 'FileEdit',
    route: 'technical-brief',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['brief', 'scope', 'technical', 'deliverables'],
  },
  {
    id: 'doc_control_issue',
    label: 'Document Control Issue Sheet',
    category: 'document_control',
    description: 'Generate a document transmittal / issue sheet for drawings, specs, or reports. Standalone output with tracking number.',
    roles: ['architect', 'bep', 'engineer', 'contractor', 'subcontractor'],
    icon: 'Send',
    route: 'standalone/doc-issue',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['document', 'transmittal', 'issue', 'tracking', 'control'],
  },
  {
    id: 'cpd_standalone',
    label: 'CPD Assessment (Standalone)',
    category: 'cpd',
    description: 'Take a CPD assessment to earn credits. Independent of any project — personal professional development record.',
    roles: ['architect', 'bep', 'engineer', 'quantity_surveyor', 'town_planner', 'cpm', 'land_surveyor', 'landscape_architect'],
    icon: 'BookOpen',
    route: 'cpd-assessment',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['CPD', 'assessment', 'credits', 'SACAP', 'ECSA', 'development'],
  },

  // ===== Client =====
  {
    id: 'soft_cost_estimator',
    label: 'Soft Cost Estimator',
    category: 'fee_calculator',
    description: 'Estimate likely professional fees + municipal costs for a project. No appointment needed — planning-stage projection.',
    roles: ['client', 'developer'],
    icon: 'Calculator',
    route: 'standalone/soft-cost',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['cost', 'estimate', 'professional', 'municipal', 'budget'],
  },
  {
    id: 'brief_wizard',
    label: 'Guided Brief Wizard (Standalone)',
    category: 'briefing',
    description: 'Create or refine a project brief independently. Save as draft and assign to an architect later.',
    roles: ['client'],
    icon: 'ClipboardEdit',
    route: 'client-intake',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['brief', 'wizard', 'client', 'requirements'],
  },
  {
    id: 'proposal_comparison',
    label: 'BEP Proposal Comparison',
    category: 'proposal',
    description: 'Compare professional proposals side-by-side: fee, scope, exclusions, timeline. No project context required.',
    roles: ['client'],
    icon: 'Scale',
    route: 'client-proposals',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['proposal', 'comparison', 'BEP', 'fee', 'selection'],
  },
  {
    id: 'progress_viewer',
    label: 'Progress Report Viewer',
    category: 'general',
    description: 'View project progress reports by reference number. Enter any project reference — Architex or external.',
    roles: ['client'],
    icon: 'Clock',
    route: 'client-progress',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['progress', 'report', 'status', 'client'],
  },
  {
    id: 'payment_dashboard',
    label: 'Payment Status Dashboard',
    category: 'payment',
    description: 'View payment status for any active project or standalone claim references. No active project needed.',
    roles: ['client', 'contractor', 'subcontractor', 'supplier'],
    icon: 'CreditCard',
    route: 'payments',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['payment', 'status', 'claim', 'invoice', 'tracking'],
  },

  // ===== Contractor =====
  {
    id: 'boq_takeoff',
    label: 'BoQ / BoM Takeoff Tool',
    category: 'estimating',
    description: 'Create a bill of quantities or materials takeoff from scratch. Manual quantity entry with rate build-up and total calculation.',
    roles: ['contractor', 'subcontractor', 'quantity_surveyor', 'architect'],
    icon: 'Ruler',
    route: 'standalone/boq-takeoff',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['BoQ', 'BoM', 'takeoff', 'quantity', 'estimate', 'material'],
  },
  {
    id: 'site_diary_entry',
    label: 'Site Diary Standalone Entry',
    category: 'site_management',
    description: 'Capture a standalone site diary entry: weather, labour, plant, deliveries, activities, delays, photos.',
    roles: ['contractor', 'subcontractor', 'site_manager'],
    icon: 'ClipboardList',
    route: 'standalone/site-diary',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['site', 'diary', 'daily', 'log', 'progress', 'photo'],
  },
  {
    id: 'rfi_generator',
    label: 'RFI / Site Instruction Generator',
    category: 'site_management',
    description: 'Draft a Request for Information or Site Instruction from scratch. Independent of any project record.',
    roles: ['contractor', 'subcontractor', 'architect', 'engineer', 'site_manager'],
    icon: 'MessageSquare',
    route: 'standalone/rfi',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['RFI', 'instruction', 'site', 'communication', 'query'],
  },
  {
    id: 'workforce_timesheet',
    label: 'Workforce Timesheet / Payroll Export',
    category: 'workforce',
    description: 'Create a workforce timesheet with hours, rates, cost codes, and PAYE/UIF/SDL fields. Export to payroll format.',
    roles: ['contractor', 'subcontractor', 'site_manager'],
    icon: 'Users',
    route: 'standalone/timesheet',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['timesheet', 'workforce', 'labour', 'payroll', 'attendance'],
  },
  {
    id: 'plant_register',
    label: 'Plant & Equipment Register',
    category: 'plant_equipment',
    description: 'Maintain a standalone register of plant/equipment: asset details, hire rates, service reminders, utilisation.',
    roles: ['contractor', 'subcontractor', 'site_manager'],
    icon: 'Wrench',
    route: 'standalone/plant-register',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['plant', 'equipment', 'asset', 'register', 'hire'],
  },
  {
    id: 'tender_bid_bench',
    label: 'Tender / Bid Workbench',
    category: 'tendering',
    description: 'Prepare a tender or bid response independently. BOQ pricing, methodology, exclusions, qualifications.',
    roles: ['contractor', 'subcontractor', 'supplier'],
    icon: 'Briefcase',
    route: 'procurement',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['tender', 'bid', 'pricing', 'BOQ', 'submission'],
  },
  {
    id: 'snag_creator',
    label: 'Snag List Creator',
    category: 'site_management',
    description: 'Create a standalone snag/punch list with photos, location, due dates, responsible party. No project or inspection needed.',
    roles: ['contractor', 'subcontractor', 'architect', 'client', 'site_manager'],
    icon: 'ClipboardCheck',
    route: 'standalone/snag-list',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['snag', 'punch', 'defect', 'inspection', 'closeout'],
  },
  {
    id: 'material_procurement',
    label: 'Material Procurement / Order List',
    category: 'procurement',
    description: 'Create a standalone material procurement list from takeoff or manual entry. Convert to purchase order-ready format.',
    roles: ['contractor', 'subcontractor', 'supplier'],
    icon: 'Package',
    route: 'standalone/procurement-list',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['material', 'procurement', 'order', 'purchase', 'list'],
  },
  {
    id: 'payment_claim_builder',
    label: 'Payment Claim Builder',
    category: 'payment',
    description: 'Build a payment claim from timesheet + material + plant data. Standalone calculation with progress evidence upload.',
    roles: ['contractor', 'subcontractor', 'freelancer'],
    icon: 'Receipt',
    route: 'standalone/payment-claim',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['payment', 'claim', 'invoice', 'progress', 'evidence'],
  },

  // ===== Subcontractor =====
  {
    id: 'shop_drawing_submission',
    label: 'Shop Drawing & Sample Submission',
    category: 'document_control',
    description: 'Submit shop drawings and material samples independently. Tag with project reference later.',
    roles: ['subcontractor', 'supplier'],
    icon: 'Upload',
    route: 'standalone/shop-drawing',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['shop drawing', 'sample', 'submission', 'approval'],
  },
  {
    id: 'package_scope_viewer',
    label: 'Package Scope Viewer',
    category: 'general',
    description: 'Enter a subcontract package reference to view scope, deliverables, and payment terms. Standalone lookup tool.',
    roles: ['subcontractor'],
    icon: 'Search',
    route: 'packages',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['package', 'scope', 'subcontract', 'deliverables'],
  },
  {
    id: 'snag_evidence_upload',
    label: 'Snag / Closeout Evidence Upload',
    category: 'closeout',
    description: 'Upload evidence of completed snag items or defects closeout. Standalone with optional project reference.',
    roles: ['subcontractor', 'contractor'],
    icon: 'Camera',
    route: 'standalone/snag-evidence',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['snag', 'closeout', 'evidence', 'photo', 'defect'],
  },
  {
    id: 'rfi_response',
    label: 'RFI / Site Instruction Response',
    category: 'site_management',
    description: 'Respond to an RFI or site instruction. Enter RFI reference manually or create a new standalone response thread.',
    roles: ['subcontractor', 'contractor', 'supplier'],
    icon: 'Reply',
    route: 'standalone/rfi-response',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['RFI', 'response', 'instruction', 'site'],
  },

  // ===== Supplier =====
  {
    id: 'catalogue_manager',
    label: 'Catalogue / Product Data Manager',
    category: 'supplier',
    description: 'Manage product catalogue, alternatives, availability, prices, and lead times. Standalone supplier dashboard.',
    roles: ['supplier'],
    icon: 'Book',
    route: 'standalone/catalogue',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['catalogue', 'product', 'data', 'price', 'supplier'],
  },
  {
    id: 'quote_response',
    label: 'Quote Response Form',
    category: 'supplier',
    description: 'Submit a quote in response to an RFQ. Enter RFQ number manually or create a proactive quote.',
    roles: ['supplier'],
    icon: 'FileInput',
    route: 'packages',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['quote', 'RFQ', 'response', 'pricing'],
  },
  {
    id: 'delivery_note',
    label: 'Delivery Note Builder',
    category: 'supplier',
    description: 'Create a delivery note with line items, quantities, PO reference, delivery details. No purchase order required.',
    roles: ['supplier', 'contractor'],
    icon: 'Truck',
    route: 'standalone/delivery-note',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['delivery', 'note', 'POD', 'goods', 'transport'],
  },
  {
    id: 'warranty_upload',
    label: 'Warranty Certificate Uploader',
    category: 'closeout',
    description: 'Upload warranty certificates and product documentation. Standalone with optional project/PO reference.',
    roles: ['supplier', 'contractor', 'subcontractor'],
    icon: 'Shield',
    route: 'standalone/warranty',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['warranty', 'certificate', 'upload', 'documentation'],
  },

  // ===== Freelancer =====
  {
    id: 'cad_upload_check',
    label: 'CAD / BIM File Upload + Drawing Checker',
    category: 'drawing',
    description: 'Upload CAD/BIM files for AI drawing check. Standalone — no BEP project assignment required. Supervisor sign-off gate applies.',
    roles: ['freelancer'],
    icon: 'FileUp',
    route: 'drawing-checker',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['CAD', 'BIM', 'drawing', 'upload', 'check', 'freelancer'],
  },
  {
    id: 'freelancer_timesheet',
    label: 'Timesheet / Claim Builder',
    category: 'freelancer',
    description: 'Submit a standalone timesheet with hours, rate, and deliverable notes. Convert to claim with supervisor approval gate.',
    roles: ['freelancer'],
    icon: 'Clock',
    route: 'standalone/freelancer-timesheet',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['timesheet', 'claim', 'freelancer', 'hours', 'payment'],
  },
  {
    id: 'deliverable_submission',
    label: 'Deliverable Submission with Sign-off',
    category: 'freelancer',
    description: 'Submit a standalone deliverable with supervisor sign-off gate. Independent of any active BEP engagement.',
    roles: ['freelancer'],
    icon: 'Send',
    route: 'freelancer-submissions',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: true,
    recentRunsCount: 0,
    tags: ['deliverable', 'submission', 'sign-off', 'freelancer', 'supervisor'],
  },
  {
    id: 'freelancer_resource_centre',
    label: 'Resource Centre / Checklists',
    category: 'resource_centre',
    description: 'Access checklists, templates, and reference resources as a freelancer. Quality control tools independent of projects.',
    roles: ['freelancer', 'architect', 'bep', 'engineer'],
    icon: 'Library',
    route: 'resource-centre',
    standaloneOnly: false,
    requiresInput: false,
    canExport: false,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['resource', 'checklist', 'template', 'reference', 'freelancer'],
  },

  // ===== Admin =====
  {
    id: 'admin_governance',
    label: 'Governance Console',
    category: 'admin_governance',
    description: 'System-wide governance overview: users, projects, verification, disputes, audit queues.',
    roles: ['admin'],
    icon: 'Settings2',
    route: 'admin-console',
    standaloneOnly: false,
    requiresInput: false,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['admin', 'governance', 'console', 'oversight'],
  },
  {
    id: 'audit_trail_viewer',
    label: 'Audit Trail Viewer',
    category: 'admin_governance',
    description: 'Browse all auditable actions across the platform. Filter by user, action, date range, entity type.',
    roles: ['admin'],
    icon: 'History',
    route: 'disputes',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['audit', 'trail', 'history', 'admin', 'compliance'],
  },
  {
    id: 'ai_review_queue',
    label: 'AI Review Queue',
    category: 'admin_governance',
    description: 'Review AI-generated outputs that require human confirmation before release or action.',
    roles: ['admin'],
    icon: 'Bot',
    route: 'ai',
    standaloneOnly: false,
    requiresInput: false,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['AI', 'review', 'queue', 'approval', 'governance'],
  },
  {
    id: 'payment_rate_config',
    label: 'Payment Rate Configurator',
    category: 'admin_governance',
    description: 'Configure payment rails, platform fees, escrow settings, and tariff tables.',
    roles: ['admin'],
    icon: 'DollarSign',
    route: 'payments',
    standaloneOnly: false,
    requiresInput: true,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['payment', 'rate', 'fee', 'escrow', 'config', 'admin'],
  },
  {
    id: 'user_verification_console',
    label: 'User Verification Console',
    category: 'admin_governance',
    description: 'Verify user identities, professional registrations, PI insurance documents. Independent dashboard.',
    roles: ['admin'],
    icon: 'ShieldCheck',
    route: 'standalone/verification-console',
    standaloneOnly: true,
    requiresInput: false,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['verification', 'user', 'identity', 'registration', 'admin'],
  },
  {
    id: 'fee_tariff_editor',
    label: 'Fee / Tariff Table Editor',
    category: 'admin_governance',
    description: 'Edit professional fee guideline tables, tariff brackets, and calculator data versions.',
    roles: ['admin'],
    icon: 'Table',
    route: 'standalone/tariff-editor',
    standaloneOnly: true,
    requiresInput: true,
    canExport: true,
    canAssignToProject: false,
    recentRunsCount: 0,
    tags: ['fee', 'tariff', 'table', 'editor', 'calculator', 'admin'],
  },
]

export function getToolsForRole(role: string): StandaloneToolDef[] {
  return STANDALONE_TOOL_REGISTRY.filter(t => t.roles.includes(role))
}

export function getToolById(id: string): StandaloneToolDef | undefined {
  return STANDALONE_TOOL_REGISTRY.find(t => t.id === id)
}

export function searchTools(query: string, role: string): StandaloneToolDef[] {
  const q = query.toLowerCase().trim()
  if (!q) return getToolsForRole(role)
  return getToolsForRole(role).filter(t =>
    t.label.toLowerCase().includes(q) ||
    t.description.toLowerCase().includes(q) ||
    t.tags.some(tag => tag.toLowerCase().includes(q)) ||
    t.category.toLowerCase().includes(q)
  )
}

export function getToolsByCategory(role: string): Record<string, StandaloneToolDef[]> {
  const tools = getToolsForRole(role)
  const grouped: Record<string, StandaloneToolDef[]> = {}
  for (const t of tools) {
    if (!grouped[t.category]) grouped[t.category] = []
    grouped[t.category].push(t)
  }
  return grouped
}
