/**
 * Fee Tracker Service
 *
 * Pure business logic for professional fee tracking. Supports:
 * - Defining project fee structures (lump sum, time-based, percentage of construction cost)
 * - Calculating per-stage breakdown (agreed fee, time costs, disbursements, net position)
 * - Fee health monitoring (warning at 80%, over-run at 100%)
 * - Writing fee health metrics into Project Passport
 *
 * This service operates on typed objects (dependency injection pattern)
 * with no Firestore dependencies.
 *
 * Requirements: 4.1, 4.2, 4.3, 4.4, 4.5
 * @module practiceManagement/feeTrackerService
 */

import type {
  FeeBasis,
  FeeHealthMetrics,
  FeeStageAllocation,
  FeeStageBreakdown,
  ProjectFeeStructure,
  SacapWorkStage,
} from './types';

// ─── Input Types ─────────────────────────────────────────────────────────────

/** Input for defining a project fee structure */
export interface DefineProjectFeeInput {
  firmId: string;
  projectId: string;
  totalAgreedFeeCents: number;
  feeBasis: FeeBasis;
  constructionCostCents?: number;
  stageBreakdown: StageAllocationInput[];
  createdBy: string;
}

/** Input for a single stage allocation */
export interface StageAllocationInput {
  stage: SacapWorkStage;
  /** Percentage of total fee allocated to this stage (for percentage-based fees) */
  percentage?: number;
  /** Fixed amount in cents allocated to this stage (for lump_sum / time_based fees) */
  fixedAmountCents?: number;
}

/** Per-stage cost data injected for breakdown calculation */
export interface StageCostData {
  stage: SacapWorkStage;
  timeCostsCents: number;
  disbursementsCents: number;
}

/** Warning/risk entry generated by fee health checks */
export interface FeeWarning {
  type: 'warning' | 'over_run';
  stage: SacapWorkStage;
  percentUsed: number;
  message: string;
}

/** Fee health result with metrics and any generated warnings/risks */
export interface FeeHealthResult {
  metrics: FeeHealthMetrics;
  warnings: FeeWarning[];
}

// ─── Constants ───────────────────────────────────────────────────────────────

/** Cost threshold percentage that triggers a warning notification */
export const WARNING_THRESHOLD_PERCENT = 80;

/** Cost threshold percentage that flags a stage as over-run */
export const OVERRUN_THRESHOLD_PERCENT = 100;

// ─── Service Functions ───────────────────────────────────────────────────────

/**
 * Defines a project's professional fee structure.
 *
 * Validates: Requirement 4.1
 * WHEN a project's professional fee structure is defined, THE Fee_Tracker SHALL require
 * total agreed fee, fee basis (lump sum, time-based, percentage of construction cost),
 * and fee breakdown by SACAP_Work_Stage.
 *
 * @param input - The fee definition input
 * @returns The newly created ProjectFeeStructure
 * @throws Error if construction cost is required but not provided for percentage basis
 * @throws Error if stage percentages don't sum to 100 for percentage basis
 * @throws Error if stage fixed amounts don't sum to total fee for lump_sum/time_based
 */
export function defineProjectFee(input: DefineProjectFeeInput): ProjectFeeStructure {
  const { firmId, projectId, totalAgreedFeeCents, feeBasis, constructionCostCents, stageBreakdown, createdBy } = input;

  // Validate percentage basis requires construction cost
  if (feeBasis === 'percentage_of_construction_cost' && (!constructionCostCents || constructionCostCents <= 0)) {
    throw new Error('constructionCostCents is required for percentage_of_construction_cost fee basis');
  }

  // Calculate allocated fee per stage
  const allocations = calculateStageAllocations(stageBreakdown, totalAgreedFeeCents, feeBasis);

  const now = new Date().toISOString();
  const id = `fee_${firmId}_${projectId}_${Date.now()}`;

  return {
    id,
    firmId,
    projectId,
    totalAgreedFeeCents,
    feeBasis,
    constructionCostCents: feeBasis === 'percentage_of_construction_cost' ? constructionCostCents : undefined,
    stageBreakdown: allocations,
    createdBy,
    createdAt: now,
    updatedAt: now,
  };
}

/**
 * Calculates per-stage breakdown showing agreed fee, time costs, disbursements, and net position.
 *
 * Validates: Requirement 4.2
 * THE Fee_Tracker SHALL display per-stage breakdown showing agreed fee, time costs incurred
 * (from approved timesheets), disbursements incurred, and net position (fee minus costs).
 *
 * @param feeStructure - The project's fee structure definition
 * @param stageCosts - Actual costs incurred per stage (from approved timesheets and expenses)
 * @returns Array of FeeStageBreakdown showing health per stage
 */
export function getStageBreakdown(
  feeStructure: ProjectFeeStructure,
  stageCosts: StageCostData[],
): FeeStageBreakdown[] {
  return feeStructure.stageBreakdown.map((allocation) => {
    const costs = stageCosts.find((c) => c.stage === allocation.stage);
    const timeCostsCents = costs?.timeCostsCents ?? 0;
    const disbursementsCents = costs?.disbursementsCents ?? 0;
    const totalCostsCents = timeCostsCents + disbursementsCents;
    const netPositionCents = allocation.allocatedFeeCents - totalCostsCents;
    const percentUsed = allocation.allocatedFeeCents > 0
      ? (totalCostsCents / allocation.allocatedFeeCents) * 100
      : 0;

    return {
      stage: allocation.stage,
      agreedFeeCents: allocation.allocatedFeeCents,
      timeCostsCents,
      disbursementsCents,
      netPositionCents,
      percentUsed,
      status: determineStageStatus(percentUsed),
    };
  });
}

/**
 * Checks overall fee health for a project and generates warnings/risks.
 *
 * Validates: Requirements 4.3, 4.4, 4.5
 * - WHEN time costs for a stage exceed 80% of the agreed stage fee, generate a warning
 * - WHEN time costs for a stage exceed 100% of the agreed stage fee, flag as over-run
 * - Write fee health metrics into Project Passport
 *
 * @param feeStructure - The project's fee structure definition
 * @param stageCosts - Actual costs incurred per stage
 * @returns FeeHealthResult with metrics and any generated warnings
 */
export function checkFeeHealth(
  feeStructure: ProjectFeeStructure,
  stageCosts: StageCostData[],
): FeeHealthResult {
  const breakdown = getStageBreakdown(feeStructure, stageCosts);
  const warnings: FeeWarning[] = [];
  const overRunStages: SacapWorkStage[] = [];
  const warningStages: SacapWorkStage[] = [];

  for (const stage of breakdown) {
    if (stage.status === 'over_run') {
      overRunStages.push(stage.stage);
      warnings.push({
        type: 'over_run',
        stage: stage.stage,
        percentUsed: stage.percentUsed,
        message: `Stage ${stage.stage} costs exceed 100% of agreed fee (${stage.percentUsed.toFixed(1)}% used). Stage flagged as over-run.`,
      });
    } else if (stage.status === 'warning') {
      warningStages.push(stage.stage);
      warnings.push({
        type: 'warning',
        stage: stage.stage,
        percentUsed: stage.percentUsed,
        message: `Stage ${stage.stage} costs exceed 80% of agreed fee (${stage.percentUsed.toFixed(1)}% used). Warning: approaching over-run.`,
      });
    }
  }

  const totalCostsIncurredCents = breakdown.reduce(
    (sum, s) => sum + s.timeCostsCents + s.disbursementsCents,
    0,
  );

  const metrics: FeeHealthMetrics = {
    projectId: feeStructure.projectId,
    totalFeeCents: feeStructure.totalAgreedFeeCents,
    totalCostsIncurredCents,
    netPositionCents: feeStructure.totalAgreedFeeCents - totalCostsIncurredCents,
    overRunStages,
    warningStages,
  };

  return { metrics, warnings };
}

// ─── Internal Helpers ────────────────────────────────────────────────────────

/**
 * Calculates the allocated fee in cents for each stage based on the fee basis.
 *
 * For percentage-based: allocatedFeeCents = totalFee * (percentage / 100)
 * For lump_sum / time_based: allocatedFeeCents = fixedAmountCents (or proportional split)
 */
function calculateStageAllocations(
  stageInputs: StageAllocationInput[],
  totalAgreedFeeCents: number,
  feeBasis: FeeBasis,
): FeeStageAllocation[] {
  if (feeBasis === 'percentage_of_construction_cost' || feeBasis === 'lump_sum' || feeBasis === 'time_based') {
    return stageInputs.map((input) => {
      let allocatedFeeCents: number;

      if (input.percentage !== undefined && input.percentage !== null) {
        // Percentage-based allocation
        allocatedFeeCents = Math.round(totalAgreedFeeCents * (input.percentage / 100));
      } else if (input.fixedAmountCents !== undefined && input.fixedAmountCents !== null) {
        // Fixed amount allocation
        allocatedFeeCents = input.fixedAmountCents;
      } else {
        // Default: equal split across stages
        allocatedFeeCents = Math.round(totalAgreedFeeCents / stageInputs.length);
      }

      return {
        stage: input.stage,
        percentage: input.percentage,
        fixedAmountCents: input.fixedAmountCents,
        allocatedFeeCents,
      };
    });
  }

  // Fallback: equal split
  return stageInputs.map((input) => ({
    stage: input.stage,
    percentage: input.percentage,
    fixedAmountCents: input.fixedAmountCents,
    allocatedFeeCents: Math.round(totalAgreedFeeCents / stageInputs.length),
  }));
}

/**
 * Determines the health status of a stage based on percent of fee used.
 *
 * Validates: Requirements 4.3, 4.4
 * - >= 100%: over_run
 * - >= 80%: warning
 * - < 80%: healthy
 */
function determineStageStatus(percentUsed: number): 'healthy' | 'warning' | 'over_run' {
  if (percentUsed >= OVERRUN_THRESHOLD_PERCENT) return 'over_run';
  if (percentUsed >= WARNING_THRESHOLD_PERCENT) return 'warning';
  return 'healthy';
}
