// @vitest-environment node
/**
 * Property-based tests — Copilot validation and guardrails.
 *
 * Feature: ai-copilot-workspace
 *
 * Property 26: Prompt Validation
 *   Validates: Requirements 12.7
 *   For any user prompt that is whitespace-only, fewer than 3 characters, or
 *   exceeds 4000 characters, the request must be rejected with a validation message.
 *
 * Property 27: Response Truncation
 *   Validates: Requirements 12.9
 *   For any AI response exceeding 8000 characters, truncateResponse() must truncate
 *   to at most 8000 chars and append "... [response truncated]".
 *   For responses ≤ 8000, they pass through unchanged.
 *
 * Property 17: Disclaimer Invariant
 *   Validates: Requirements 12.3
 *   For any response generated by the CopilotService (regardless of capability),
 *   appendDisclaimer() must append "AI-generated content. Review before professional use."
 *
 * Property 18: Copyrighted Text Limit
 *   Validates: Requirements 10.4
 *   For any clause explanation output, no sequence of more than 15 consecutive words
 *   from copyrighted contract forms should appear. checkCopyrightCompliance() must flag violations.
 *
 * Uses fast-check with minimum 100 iterations per property test.
 */

import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import { CopilotMessageInputSchema } from '@/lib/copilotSchemas';
import {
  truncateResponse,
  appendDisclaimer,
  checkCopyrightCompliance,
  applyGuardrails,
} from '@/services/copilotGuardrailFilter';

// ══════════════════════════════════════════════════════════════════════════════
// Property 26: Prompt Validation
// Feature: ai-copilot-workspace, Property 26: Prompt Validation
// Validates: Requirements 12.7
// ══════════════════════════════════════════════════════════════════════════════

describe('Feature: ai-copilot-workspace, Property 26: Prompt Validation', () => {
  /**
   * **Validates: Requirements 12.7**
   *
   * Prompts must be 3–4000 characters and not whitespace-only.
   * Uses Zod schema CopilotMessageInputSchema from src/lib/copilotSchemas.ts.
   */

  it('accepts any prompt with 3–4000 chars containing at least 3 non-whitespace characters', () => {
    fc.assert(
      fc.property(
        // Generate strings with guaranteed non-whitespace content
        fc.array(fc.integer({ min: 33, max: 126 }), { minLength: 3, maxLength: 100 }),
        fc.array(fc.constantFrom(' ', '\t', '\n'), { minLength: 0, maxLength: 50 }),
        (nonWsCodes, wsChars) => {
          const nonWs = nonWsCodes.map((c) => String.fromCharCode(c)).join('');
          const text = nonWs + wsChars.join('');
          fc.pre(text.length >= 3 && text.length <= 4000);

          const result = CopilotMessageInputSchema.safeParse({ prompt: text });
          expect(result.success).toBe(true);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('rejects any prompt shorter than 3 characters', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 0, maxLength: 2 }),
        (text) => {
          const result = CopilotMessageInputSchema.safeParse({ prompt: text });
          expect(result.success).toBe(false);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('rejects any prompt exceeding 4000 characters', () => {
    fc.assert(
      fc.property(
        fc.array(fc.integer({ min: 33, max: 126 }), { minLength: 50, maxLength: 200 }),
        fc.integer({ min: 3801, max: 4500 }),
        (nonWsCodes, totalLength) => {
          const base = nonWsCodes.map((c) => String.fromCharCode(c)).join('');
          const text = base + 'a'.repeat(Math.max(0, totalLength - base.length));
          fc.pre(text.length > 4000);

          const result = CopilotMessageInputSchema.safeParse({ prompt: text });
          expect(result.success).toBe(false);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('rejects any whitespace-only prompt (even if 3+ chars)', () => {
    fc.assert(
      fc.property(
        fc.array(fc.constantFrom(' ', '\t', '\n', '\r', '\f', '\v'), { minLength: 3, maxLength: 200 }),
        (wsChars) => {
          const text = wsChars.join('');
          fc.pre(text.trim().length < 3);

          const result = CopilotMessageInputSchema.safeParse({ prompt: text });
          expect(result.success).toBe(false);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('accepts prompts at exactly 3 non-whitespace characters', () => {
    fc.assert(
      fc.property(
        fc.array(fc.integer({ min: 33, max: 126 }), { minLength: 3, maxLength: 3 }),
        (codes) => {
          const text = codes.map((c) => String.fromCharCode(c)).join('');
          const result = CopilotMessageInputSchema.safeParse({ prompt: text });
          expect(result.success).toBe(true);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('accepts prompts at exactly 4000 characters with non-whitespace content', () => {
    fc.assert(
      fc.property(
        fc.array(fc.integer({ min: 33, max: 126 }), { minLength: 10, maxLength: 50 }),
        (codes) => {
          const base = codes.map((c) => String.fromCharCode(c)).join('');
          const text = base + 'x'.repeat(4000 - base.length);
          expect(text.length).toBe(4000);
          const result = CopilotMessageInputSchema.safeParse({ prompt: text });
          expect(result.success).toBe(true);
        },
      ),
      { numRuns: 100 },
    );
  });
});

// ══════════════════════════════════════════════════════════════════════════════
// Property 27: Response Truncation
// Feature: ai-copilot-workspace, Property 27: Response Truncation
// Validates: Requirements 12.9
// ══════════════════════════════════════════════════════════════════════════════

const TRUNCATION_INDICATOR = '... [response truncated]';
const MAX_LENGTH = 8000;

describe('Feature: ai-copilot-workspace, Property 27: Response Truncation', () => {
  /**
   * **Validates: Requirements 12.9**
   *
   * For any response exceeding 8000 characters, truncateResponse() must truncate
   * to at most 8000 chars and append the truncation indicator.
   * For responses ≤ 8000 chars, they pass through unchanged.
   */

  it('passes through responses of 8000 chars or fewer unchanged', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 0, maxLength: MAX_LENGTH }),
        (content) => {
          const result = truncateResponse(content);
          expect(result.content).toBe(content);
          expect(result.truncated).toBe(false);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('truncates responses exceeding 8000 chars to at most 8000 chars', () => {
    fc.assert(
      fc.property(
        // Generate long strings guaranteed to exceed 8000 chars
        fc.array(fc.integer({ min: 33, max: 126 }), { minLength: 100, maxLength: 300 }),
        fc.integer({ min: 7800, max: 12000 }),
        (codes, extraLength) => {
          const base = codes.map((c) => String.fromCharCode(c)).join('');
          const content = base + ' word'.repeat(Math.ceil((extraLength - base.length) / 5));
          fc.pre(content.length > MAX_LENGTH);

          const result = truncateResponse(content);
          expect(result.content.length).toBeLessThanOrEqual(MAX_LENGTH);
          expect(result.truncated).toBe(true);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('appends truncation indicator when response is truncated', () => {
    fc.assert(
      fc.property(
        fc.array(fc.integer({ min: 33, max: 126 }), { minLength: 100, maxLength: 300 }),
        fc.integer({ min: 7800, max: 12000 }),
        (codes, extraLength) => {
          const base = codes.map((c) => String.fromCharCode(c)).join('');
          const content = base + ' word'.repeat(Math.ceil((extraLength - base.length) / 5));
          fc.pre(content.length > MAX_LENGTH);

          const result = truncateResponse(content);
          expect(result.content).toContain(TRUNCATION_INDICATOR);
          expect(result.content.endsWith(TRUNCATION_INDICATOR)).toBe(true);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('never exceeds 8000 chars regardless of input size', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 0, maxLength: 20000 }),
        (content) => {
          const result = truncateResponse(content);
          expect(result.content.length).toBeLessThanOrEqual(MAX_LENGTH);
        },
      ),
      { numRuns: 200 },
    );
  });

  it('marks truncated=false only when content length ≤ 8000', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 0, maxLength: 20000 }),
        (content) => {
          const result = truncateResponse(content);
          if (content.length <= MAX_LENGTH) {
            expect(result.truncated).toBe(false);
            expect(result.content).toBe(content);
          } else {
            expect(result.truncated).toBe(true);
          }
        },
      ),
      { numRuns: 200 },
    );
  });
});

// ══════════════════════════════════════════════════════════════════════════════
// Property 17: Disclaimer Invariant
// Feature: ai-copilot-workspace, Property 17: Disclaimer Invariant
// Validates: Requirements 12.3
// ══════════════════════════════════════════════════════════════════════════════

const DISCLAIMER = '\n\nAI-generated content. Review before professional use.';

describe('Feature: ai-copilot-workspace, Property 17: Disclaimer Invariant', () => {
  /**
   * **Validates: Requirements 12.3**
   *
   * For any response processed by the Copilot guardrails, the disclaimer
   * "AI-generated content. Review before professional use." must be appended.
   */

  it('appendDisclaimer always appends the disclaimer to any string', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 0, maxLength: 5000 }),
        (content) => {
          const result = appendDisclaimer(content);
          expect(result.endsWith('AI-generated content. Review before professional use.')).toBe(
            true,
          );
        },
      ),
      { numRuns: 100 },
    );
  });

  it('appendDisclaimer preserves original content as a prefix', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 0, maxLength: 5000 }),
        (content) => {
          const result = appendDisclaimer(content);
          expect(result).toBe(content + DISCLAIMER);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('applyGuardrails always produces output ending with the disclaimer', () => {
    fc.assert(
      fc.property(
        // Generate safe content (no profanity, no PII) to test guardrails pipeline
        fc.array(fc.integer({ min: 65, max: 90 }), { minLength: 5, maxLength: 200 }),
        (codes) => {
          const content = codes.map((c) => String.fromCharCode(c)).join(' ');
          const result = applyGuardrails(content);
          expect(
            result.content.endsWith('AI-generated content. Review before professional use.'),
          ).toBe(true);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('applyGuardrails appends disclaimer even after truncation', () => {
    fc.assert(
      fc.property(
        // Generate long safe content that will trigger truncation
        fc.array(fc.integer({ min: 65, max: 90 }), { minLength: 100, maxLength: 300 }),
        fc.integer({ min: 7800, max: 12000 }),
        (codes, extraLength) => {
          const base = codes.map((c) => String.fromCharCode(c)).join(' ');
          const content = base + ' word'.repeat(Math.ceil((extraLength - base.length) / 5));
          fc.pre(content.length > MAX_LENGTH);

          const result = applyGuardrails(content);
          expect(
            result.content.endsWith('AI-generated content. Review before professional use.'),
          ).toBe(true);
        },
      ),
      { numRuns: 100 },
    );
  });
});

// ══════════════════════════════════════════════════════════════════════════════
// Property 18: Copyrighted Text Limit
// Feature: ai-copilot-workspace, Property 18: Copyrighted Text Limit
// Validates: Requirements 10.4
// ══════════════════════════════════════════════════════════════════════════════

describe('Feature: ai-copilot-workspace, Property 18: Copyrighted Text Limit', () => {
  /**
   * **Validates: Requirements 10.4**
   *
   * For any clause explanation output, no sequence of more than 15 consecutive words
   * from copyrighted contract forms should appear. checkCopyrightCompliance() must
   * flag violations.
   */

  it('flags content with legal phrases exceeding 15 consecutive words', () => {
    fc.assert(
      fc.property(
        // Generate legal-sounding contract phrases that trigger pattern matching
        fc.constantFrom(
          'the contractor shall be liable',
          'the employer shall not be responsible',
          'notwithstanding anything contained in this',
          'subject to the provisions of clause',
          'without prejudice to the generality of the',
          'the principal agent shall issue',
          'practical completion shall be deemed to have been achieved',
        ),
        // Add enough trailing words to exceed 15 consecutive
        fc.array(
          fc.constantFrom(
            'and',
            'the',
            'provisions',
            'of',
            'this',
            'contract',
            'shall',
            'apply',
            'to',
            'all',
            'parties',
            'hereto',
            'binding',
            'upon',
            'execution',
          ),
          { minLength: 12, maxLength: 20 },
        ),
        (legalPhrase, trailingWords) => {
          const content = legalPhrase + ' ' + trailingWords.join(' ');
          // Count total words from match point
          const words = content.trim().split(/\s+/);
          fc.pre(words.length > 15);

          const result = checkCopyrightCompliance(content);
          expect(result.compliant).toBe(false);
          expect(result.violations.length).toBeGreaterThan(0);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('allows content with legal phrases of 15 or fewer consecutive words', () => {
    fc.assert(
      fc.property(
        fc.constantFrom(
          'the contractor shall be liable for damages',
          'the employer shall pay within 30 days',
          'subject to the provisions of clause 12',
          'without prejudice to the generality',
        ),
        (content) => {
          // These short legal phrases are within the 15-word limit
          const words = content.trim().split(/\s+/);
          fc.pre(words.length <= 15);

          const result = checkCopyrightCompliance(content);
          expect(result.compliant).toBe(true);
          expect(result.violations.length).toBe(0);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('passes non-legal content regardless of length', () => {
    fc.assert(
      fc.property(
        // Generate generic text that doesn't match legal patterns
        fc.array(
          fc.constantFrom(
            'The project is progressing well',
            'Team members are on schedule',
            'Budget allocation remains within limits',
            'Design review completed successfully',
            'Client meeting scheduled for next week',
            'All deliverables are on track',
          ),
          { minLength: 1, maxLength: 5 },
        ),
        (sentences) => {
          const content = sentences.join('. ') + '.';
          const result = checkCopyrightCompliance(content);
          expect(result.compliant).toBe(true);
          expect(result.violations.length).toBe(0);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('violations array contains the offending word sequences', () => {
    fc.assert(
      fc.property(
        fc.constantFrom(
          'the contractor shall be liable',
          'the employer shall not be responsible',
          'notwithstanding anything contained in this',
        ),
        fc.array(
          fc.constantFrom(
            'for',
            'all',
            'damages',
            'arising',
            'from',
            'any',
            'breach',
            'of',
            'the',
            'terms',
            'and',
            'conditions',
            'of',
            'this',
            'agreement',
          ),
          { minLength: 12, maxLength: 20 },
        ),
        (legalPhrase, trailingWords) => {
          const content = legalPhrase + ' ' + trailingWords.join(' ');
          const words = content.trim().split(/\s+/);
          fc.pre(words.length > 15);

          const result = checkCopyrightCompliance(content);
          if (!result.compliant) {
            for (const violation of result.violations) {
              const violationWords = violation.trim().split(/\s+/);
              // Violations should contain sequences of words
              expect(violationWords.length).toBeGreaterThan(0);
            }
          }
        },
      ),
      { numRuns: 100 },
    );
  });
});
