/**
 * Property-based tests — Implicit submission privacy constraint.
 *
 * Feature: intelligent-feedback-loop
 *
 * Property 15: Implicit submission privacy constraint
 *   Validates: Requirements 6.5
 *   For any implicit feedback submission generated by the friction detector,
 *   the description and metadata must contain only structural interaction data
 *   (page path, action type, error codes, element identifiers, click coordinates
 *   relative to element bounds) and must never contain form field values, document
 *   content, or chat message text.
 *
 * Uses fast-check with minimum 100 iterations per property test.
 */

import { describe, it, expect } from 'vitest';
import fc from 'fast-check';

// ══════════════════════════════════════════════════════════════════════════════
// Pure function under test — extracted from useFrictionDetector.ts
// ══════════════════════════════════════════════════════════════════════════════

const MAX_DESCRIPTION_LENGTH = 500;

/**
 * Builds the implicit submission description from structural metadata only.
 * This is the exact logic from useFrictionDetector.ts.
 */
function buildImplicitDescription(
  frictionType: string,
  pagePath: string,
  target: string,
  count: number
): string {
  const desc = `[${frictionType}] on ${pagePath} targeting ${target}: ${count} occurrences`;
  return desc.slice(0, MAX_DESCRIPTION_LENGTH);
}

// ══════════════════════════════════════════════════════════════════════════════
// Pattern definitions
// ══════════════════════════════════════════════════════════════════════════════

/** Structural data patterns that ARE allowed in the description. */
const STRUCTURAL_PATTERNS = [
  /^\[[\w_]+\]/,                              // friction type in brackets
  /on \/[\w\-\/]*/,                           // page path
  /targeting [#.\[\]a-zA-Z0-9_\-"=]+/,       // element identifier
  /\d+ occurrences$/,                         // count
];

/** Content patterns that must NEVER appear in an implicit description. */
const FORBIDDEN_PATTERNS = [
  /<form[\s>]/i,                              // form content
  /password/i,                                // credential data
  /credit.?card/i,                            // financial data
  /@[\w]+\.\w+/,                              // email addresses
  /\b\d{3}-\d{3}-\d{4}\b/,                   // phone numbers (US format)
  /\b\d{4}[\s-]?\d{4}[\s-]?\d{4}[\s-]?\d{4}\b/, // credit card numbers
  /\bssn\b/i,                                 // SSN references
  /\bsocial.?security\b/i,                    // social security references
];

// ══════════════════════════════════════════════════════════════════════════════
// Generators
// ══════════════════════════════════════════════════════════════════════════════

/** Valid friction types as used by the friction detector. */
const frictionTypeArb = fc.constantFrom(
  'repeated_errors',
  'workflow_abandonment',
  'rage_clicks'
);

/** Page paths following the /path/segment format. */
const pagePathArb = fc.array(
  fc.stringMatching(/^[a-z][a-z0-9\-]{0,20}$/),
  { minLength: 1, maxLength: 5 }
).map(segments => '/' + segments.join('/'));

/** Element identifiers following CSS selector patterns (id, data-testid, tag.class). */
const elementIdArb = fc.oneof(
  // #elementId
  fc.stringMatching(/^[a-zA-Z][a-zA-Z0-9_\-]{0,20}$/).map(id => `#${id}`),
  // [data-testid="value"]
  fc.stringMatching(/^[a-zA-Z][a-zA-Z0-9_\-]{0,20}$/).map(id => `[data-testid="${id}"]`),
  // tag.class
  fc.stringMatching(/^[a-z]{2,10}$/).chain(tag =>
    fc.stringMatching(/^[a-zA-Z][a-zA-Z0-9_\-]{0,15}$/).map(cls => `${tag}.${cls}`)
  )
);

/** Signal count — realistic range for friction signals. */
const countArb = fc.integer({ min: 3, max: 50 });

// ══════════════════════════════════════════════════════════════════════════════
// Property 15: Implicit submission privacy constraint
// Validates: Requirements 6.5
// ══════════════════════════════════════════════════════════════════════════════

describe('Feature: intelligent-feedback-loop, Property 15: Implicit submission privacy constraint', () => {
  /**
   * **Validates: Requirements 6.5**
   *
   * The description always follows the structural format:
   * [type] on path targeting element: N occurrences
   */
  it('description always follows the structural format [type] on path targeting element: N occurrences', () => {
    fc.assert(
      fc.property(
        frictionTypeArb,
        pagePathArb,
        elementIdArb,
        countArb,
        (frictionType, pagePath, target, count) => {
          const desc = buildImplicitDescription(frictionType, pagePath, target, count);

          // Must start with [frictionType]
          expect(desc).toMatch(/^\[[\w_]+\]/);
          // Must contain "on /..."
          expect(desc).toMatch(/\bon\s+\//);
          // Must contain "targeting ..."
          expect(desc).toMatch(/\btargeting\s+/);
          // Must end with "N occurrences" (unless truncated)
          if (desc.length < MAX_DESCRIPTION_LENGTH) {
            expect(desc).toMatch(/\d+\s+occurrences$/);
          }
        },
      ),
      { numRuns: 100 },
    );
  });

  /**
   * **Validates: Requirements 6.5**
   *
   * The description never exceeds 500 characters.
   */
  it('description never exceeds 500 characters', () => {
    fc.assert(
      fc.property(
        frictionTypeArb,
        pagePathArb,
        elementIdArb,
        countArb,
        (frictionType, pagePath, target, count) => {
          const desc = buildImplicitDescription(frictionType, pagePath, target, count);
          expect(desc.length).toBeLessThanOrEqual(MAX_DESCRIPTION_LENGTH);
        },
      ),
      { numRuns: 100 },
    );
  });

  /**
   * **Validates: Requirements 6.5**
   *
   * Given arbitrary page paths, element IDs, and friction types,
   * the output never contains user-entered form data patterns.
   */
  it('output never contains forbidden user-entered data patterns', () => {
    fc.assert(
      fc.property(
        frictionTypeArb,
        pagePathArb,
        elementIdArb,
        countArb,
        (frictionType, pagePath, target, count) => {
          const desc = buildImplicitDescription(frictionType, pagePath, target, count);

          for (const pattern of FORBIDDEN_PATTERNS) {
            expect(desc).not.toMatch(pattern);
          }
        },
      ),
      { numRuns: 100 },
    );
  });

  /**
   * **Validates: Requirements 6.5**
   *
   * The function only includes the 4 allowed structural fields:
   * friction type, page path, target identifier, and count.
   * No extraneous user-generated content leaks in.
   */
  it('description contains only the 4 structural fields and no extraneous content', () => {
    fc.assert(
      fc.property(
        frictionTypeArb,
        pagePathArb,
        elementIdArb,
        countArb,
        (frictionType, pagePath, target, count) => {
          const desc = buildImplicitDescription(frictionType, pagePath, target, count);
          const expected = `[${frictionType}] on ${pagePath} targeting ${target}: ${count} occurrences`;
          const expectedTruncated = expected.slice(0, MAX_DESCRIPTION_LENGTH);

          // The output must be exactly the deterministic template (possibly truncated)
          expect(desc).toBe(expectedTruncated);
        },
      ),
      { numRuns: 100 },
    );
  });

  /**
   * **Validates: Requirements 6.5**
   *
   * Even with adversarial inputs that look like PII (email-like strings,
   * phone-like strings, etc.), the structural format constrains the output
   * so that it never inadvertently contains actual user content patterns.
   * This tests that even if structural identifiers happen to contain
   * sensitive-looking patterns, the builder only includes what was passed in
   * as structural metadata.
   */
  it('with arbitrary string inputs, output is still deterministically built from only the 4 fields', () => {
    fc.assert(
      fc.property(
        fc.constantFrom('repeated_errors', 'workflow_abandonment', 'rage_clicks'),
        fc.string({ minLength: 1, maxLength: 100 }),
        fc.string({ minLength: 1, maxLength: 100 }),
        fc.integer({ min: 1, max: 999 }),
        (frictionType, pagePath, target, count) => {
          const desc = buildImplicitDescription(frictionType, pagePath, target, count);
          const expected = `[${frictionType}] on ${pagePath} targeting ${target}: ${count} occurrences`;
          const expectedTruncated = expected.slice(0, MAX_DESCRIPTION_LENGTH);

          // The deterministic template ensures no additional data leaks
          expect(desc).toBe(expectedTruncated);
          expect(desc.length).toBeLessThanOrEqual(MAX_DESCRIPTION_LENGTH);
        },
      ),
      { numRuns: 200 },
    );
  });
});
