import type { DeliveryNote, FreelancerDeliverable, FreelancerTimesheet, PaymentBlocker, QuoteResponse, ShopDrawingSubmission, WarrantyCertificate } from './types';
import { id } from './utils';

export class BlockerService {
  quote(q: QuoteResponse): PaymentBlocker[] { return q.flags.map((f) => ({ id: id('blocker'), packageId: q.packageId, sourceType: 'quote' as const, sourceId: q.id, severity: f.includes('Substitution') ? 'blocker' as const : 'warning' as const, reason: f, blocksPaymentRecommendation: f.includes('Substitution') })); }
  delivery(d: DeliveryNote): PaymentBlocker | null { if (['rejected', 'partially_accepted', 'acceptance_required'].includes(d.status)) return { id: id('blocker'), packageId: d.packageId, sourceType: 'delivery' as const, sourceId: d.id, severity: d.status === 'rejected' ? 'critical' as const : 'blocker' as const, reason: `Delivery ${d.status}: acceptance/rejection must be resolved`, blocksPaymentRecommendation: true }; return null; }
  warranty(w: WarrantyCertificate): PaymentBlocker | null { if (!w.verified) return { id: id('blocker'), packageId: w.packageId, sourceType: 'warranty' as const, sourceId: w.id, severity: 'warning' as const, reason: 'Warranty uploaded but not verified for closeout', blocksPaymentRecommendation: false }; return null; }
  shopDrawing(s: ShopDrawingSubmission): PaymentBlocker | null { if (!['approved', 'approved_with_comments'].includes(s.status)) return { id: id('blocker'), packageId: s.packageId, sourceType: 'shop_drawing' as const, sourceId: s.id, severity: 'blocker' as const, reason: `Shop drawing status ${s.status}; not approved for use`, blocksPaymentRecommendation: true }; return null; }
  deliverable(d: FreelancerDeliverable, packageId: string): PaymentBlocker | null { if (d.externalIssueBlocked) return { id: id('blocker'), packageId, sourceType: 'freelancer_deliverable' as const, sourceId: d.id, severity: 'blocker' as const, reason: 'Freelancer deliverable requires supervisor sign-off before external issue', blocksPaymentRecommendation: true }; return null; }
  timesheet(t: FreelancerTimesheet, packageId: string): PaymentBlocker | null { if (!t.supervisorApproved) return { id: id('blocker'), packageId, sourceType: 'timesheet' as const, sourceId: t.id, severity: 'blocker' as const, reason: 'Freelancer timesheet requires supervisor approval before claim', blocksPaymentRecommendation: true }; return null; }
}
